/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:39:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.admin.site;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.lang.*;
import risk.admin.site.SiteBean;
import risk.admin.site.SitegroupBean;
import risk.admin.site.SiteMng;
import risk.util.ParseRequest;
import risk.util.ConfigUtil;

public final class ifram_005ftarget_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/admin/site/../../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.admin.site.SiteMng");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.admin.site.SiteBean");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("risk.admin.site.SitegroupBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	List sglist = null;
	List sitelist = null;
	int sg=0;
	String sch = "";
	ParseRequest pr = new ParseRequest(request);

	//if( request.getParameter("sg_seq") != null ) sg = Integer.parseInt(request.getParameter("sg_seq"));
	
	//20110511 미확인된 에러 난다고 하여 int변환 숫자체크 보강
	String strSg = pr.getString("sg_seq","0");
	
	String language = pr.getString("language"); 
	
	char ch;
	for(int i = 0 ; i < strSg.length(); i++){
		ch = strSg.charAt(i);
		if(ch < 48 || ch >57){
			strSg = "0";
			break; 		
		}
	}
	sg = Integer.parseInt(strSg);
	
	
	
	if( pr.getString("tg_sch") != null ) sch = pr.getString("tg_sch");

	SiteMng sitemng = new SiteMng();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basic.css\" type=\"text/css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t<!--\r\n");
      out.write("\ttd { font-size:12px; color:#333333; font-family:\"dotum\"; ; line-height: 18px}\r\n");
      out.write("    input { font-size:12px; border:1px solid #CFCFCF; height:16px; color:#767676; }\r\n");
      out.write("\t.t {  font-family: \"Tahoma\"; font-size: 11px; color: #666666}\r\n");
      out.write("    .tCopy { font-family: \"Tahoma\"; font-size: 12px; color: #000000; font-weight: bold}\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 4px;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\tbackground-color: #F3F3F3;\r\n");
      out.write("}\r\n");
      out.write("\t-->\r\n");
      out.write("\t</style>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tfunction edit_sg()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif( tg_site.sg_seq.value ) {\r\n");
      out.write("\t\t\tvar url = \"pop_sitegroup.jsp?mode=edit&sgseq=\"+tg_site.sg_seq.value+\"&language=\"+ tg_site.language.value;\r\n");
      out.write("\t\t\twindow.open(url, \"pop_sitegroup\", \"width=400,height=150\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction del_sg()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif( tg_site.sg_seq.value ) {\r\n");
      out.write("\t\t\tif( confirm('사이트그룹을 삭제하시겠습니까?') ) {\r\n");
      out.write("\t\t\t\tlocation.href = \"ifram_target_prc.jsp?mode=del&sgseq=\"+tg_site.sg_seq.value+\"&language=\"+ tg_site.language.value;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction search_TargetSite_frm()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif( parent.target_form.tg_sch.value ) {\r\n");
      out.write("\t\t\ttg_site.tg_sch.value = parent.target_form.tg_sch.value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttg_site.submit();\r\n");
      out.write("\t}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<table  border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"padding-top:2px;\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"right\" style=\"padding-left:10px\">\r\n");
      out.write("    <table  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><img src=\"../../../images/admin/site/brank.gif\" width=\"1\" height=\"5\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<form name=\"tg_site\" action=\"ifram_target.jsp\" method=\"GET\">\r\n");
      out.write("\t  \t\t\t\t<input name=\"tg_sch\" type=\"hidden\">\r\n");
      out.write("\t\t\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../../../images/admin/site/admin_ico03.gif\"  hspace=\"3\">언어선택\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"30\"></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../../../images/admin/site/admin_ico03.gif\"  hspace=\"3\">사이트 그룹 선택\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=\"1\"><td></td></tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"140\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"language\" class=\"t\" style=\"width:140px;\" onchange=\"search_TargetSite_frm();\">\r\n");
      out.write("\t\t\t\t\t       <option value=\"\" ");
if( "".equals(language)) out.println("selected");
      out.write(">전체\r\n");
      out.write("\t\t\t\t\t       <option value=\"KOR\" ");
if( "KOR".equals(language)) out.println("selected");
      out.write(">한국어\r\n");
      out.write("\t\t\t\t\t       <option value=\"ENG\" ");
if( "ENG".equals(language)) out.println("selected");
      out.write(">영어\r\n");
      out.write("    \t\t\t\t\t </select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"30\"></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td width=\"140\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"sg_seq\" class=\"t\"  style=\"width:140px;\" onchange=\"search_TargetSite_frm();\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">전체</option>\r\n");
      out.write("\t\t\t\t\t");

						sglist = sitemng.getSGList();
					
						for(int i=0; i < sglist.size();i++) {
							SitegroupBean SGinfo = (SitegroupBean)sglist.get(i);
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(SGinfo.get_seq());
      out.write('"');
      out.write(' ');
if( SGinfo.get_seq() == sg) out.println("selected");
      out.write('>');
      out.print( SGinfo.get_name());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"1\"><td></td><tr>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("<!--      <tr>-->\r\n");
      out.write("<!--        <td><img src=\"../../../images/admin/site/admin_ico03.gif\" width=\"10\" height=\"11\" hspace=\"3\">사이트 그룹 선택</td>-->\r\n");
      out.write("<!--      </tr>-->\r\n");
      out.write("<!--\t  <form name=\"tg_site\" action=\"ifram_target.jsp\" method=\"GET\">-->\r\n");
      out.write("<!--\t  <input name=\"tg_sch\" type=\"hidden\">-->\r\n");
      out.write("<!--      <tr>-->\r\n");
      out.write("<!--        <td height=\"25\">-->\r\n");
      out.write("<!--\t\t<select name=\"sg_seq\" class=\"t\"  style=\"width:310px;\" onchange=\"search_TargetSite_frm();\">-->\r\n");
      out.write("<!--\t\t<option value=\"0\">전체</option>-->\r\n");
      out.write("<!--");
      out.write("-->\r\n");
      out.write("<!--<option value=\"");
//=SGinfo.get_seq()
      out.write('"');
      out.write(' ');
//if( SGinfo.get_seq() == sg) out.println("selected");
      out.write('>');
//= SGinfo.get_name()
      out.write("</option>-->\r\n");
      out.write("<!--");
      out.write("-->\r\n");
      out.write("<!--\t\t</select></td>-->\r\n");
      out.write("<!--      </tr>-->\r\n");
      out.write("<!--\t  </form>-->\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td align=\"right\" ><img src=\"../../../images/admin/site/btn_groupedit.gif\" width=\"72\" height=\"21\" onclick=\"edit_sg();\" style=\"cursor:hand;\"><img src=\"../../../images/admin/site/btn_groupdel.gif\" width=\"59\" height=\"21\" hspace=\"5\" onclick=\"del_sg();\" style=\"cursor:hand;\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td><img src=\"../../../images/admin/site/brank.gif\" width=\"1\" height=\"6\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"20\"><img src=\"../../../images/admin/site/admin_ico03.gif\" width=\"10\" height=\"11\" hspace=\"3\">수집사이트 리스트</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("        <form name=\"sg_mng\" action=\"ifram_source_prc.jsp\" method=\"POST\">\r\n");
      out.write("\t\t   <input type=\"hidden\" name=\"mode\" value=\"del\">\r\n");
      out.write("\t\t   <input type=\"hidden\" name=\"sgseq\">\r\n");
      out.write("\t\t   <input type=\"hidden\" name=\"code1\" >\r\n");
      out.write("        <select name=\"gsn\"  multiple style=\"width:305px;height:185px;\" class=\"t\">\r\n");

	
	sitelist = sitemng.getList(sch,sg,language);

	/*
	if( sch == null  ) {
		sitelist = sitemng.getList();
	}
	
	else if( sch != null && sg > 0 ) {
		sitelist = sitemng.getList(sch,sg);
	}else if( sch != null ) {
		sitelist = sitemng.getList(sch);
	} else if( sg == 0 ) {
		sitelist = sitemng.getList();
	} else {
		sitelist = sitemng.getList(sg);
	}
     */
    String active = "";
 	String update = "";   

	for(int i=0; i < sitelist.size();i++) {
		SiteBean siteinfo = (SiteBean)sitelist.get(i);
		active = "";
		update = "";
		if(siteinfo.getS_active().equals("0")){
			active = "style='color:#FF0000;'";
			update = "[정지]";
		}

      out.write("\r\n");
      out.write("<option ");
      out.print(active);
      out.write(" value=\"");
      out.print( siteinfo.get_gsn());
      out.write('"');
      out.write('>');
      out.print(update );
      out.print( siteinfo.get_name());
      out.write(' ');
      out.write(' ');
      out.write('(');
      out.print( siteinfo.getS_reg_date() );
      out.write(")</option>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
