/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.admin.logs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import risk.util.ConfigUtil;
import risk.util.ParseRequest;
import java.util.*;
import java.lang.*;
import risk.admin.log.LogMgr;
import risk.util.PageIndex;
import risk.admin.log.LogBean;

public final class user_005flog_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/admin/logs/../../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.util.PageIndex");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.admin.log.LogBean");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("risk.admin.log.LogMgr");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int PAGE_SIZE = 10;		//페이지당 리스트 수
	int totpage = 0;		//총 페이지수
	int nowpage = 1;		//현재 페이지번호
	int count = 0;			//총 게시물 수
	
	String sch_mode = null;	//검색조건 분류
	String sch_val = null;	//조건 값
	String logKinds = null; //로그 종류
	String logType = null; //로그 상세 종류
	
	ArrayList logKindsList = new ArrayList();
	ArrayList logTypeList = new ArrayList();
	ArrayList logList = new ArrayList();
	
	
	ParseRequest pr = new ParseRequest(request);
	
	nowpage = pr.getInt("nowpage",1);
	sch_mode = pr.getString("sch_mode","");
	sch_val = pr.getString("sch_val","");
	logKinds = pr.getString("logKinds","");
	logType = pr.getString("logType","");
	
	
	LogMgr logMgr = new LogMgr();
	LogBean logBean = new LogBean();
	logKindsList = logMgr.getLogKindsList();
	logTypeList = logMgr.getLogTypeList();
	logList = logMgr.getLogList(nowpage,10,logKinds,logType,sch_mode,sch_val);
	
	totpage = logMgr.getListCnt()/10;
	if(logMgr.getListCnt()%10!=0) totpage++;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>RISK2</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../css/base.css\" />\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tfunction init(){\r\n");
      out.write("\t\tsch_log.sch_val.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    function chg_svc() {\t\t\r\n");
      out.write("\t\tsch_log.submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function pageClick( paramUrl ) {\r\n");
      out.write("\t\tvar f = document.sch_log; \r\n");
      out.write("        f.action = 'user_log_list.jsp' + paramUrl;\r\n");
      out.write("        f.target='';\r\n");
      out.write("        f.submit();\t\t\r\n");
      out.write("    }\r\n");
      out.write("\tfunction seach() {\r\n");
      out.write("\t\tsch_log.submit();\r\n");
      out.write("\t}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin-left: 15px\">\r\n");
      out.write("<form name=\"sch_log\" action=\"user_log_list.jsp\" method=\"post\">\r\n");
      out.write("<input name=\"nowpage\" type=\"hidden\" value=\"");
      out.print(nowpage);
      out.write("\">\r\n");
      out.write("<table style=\"width:100%;height:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"body_bg_top\" valign=\"top\">\r\n");
      out.write("\t\t<table style=\"width:820px;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<!-- 타이틀 시작 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"tit_bg\" style=\"height:67px;padding-top:20px;\">\r\n");
      out.write("\t\t\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"../../../images/admin/log/tit_icon.gif\" /><img src=\"../../../images/admin/log/tit_0503.gif\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"navi_home\">HOME</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"navi_arrow\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"navi_arrow2\">로그보기</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td height=\"15\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 타이틀 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 검색 시작 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"search_box\">\r\n");
      out.write("\t\t\t\t<table id=\"search_box\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"height:30px;\">검색 조건</th>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"vertical-align:middle\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"sch_mode\" style=\"vertical-align:middle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\"  ");
 if( sch_mode.equals("") ) out.print("selected");
      out.write(">전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\" ");
 if( sch_mode.equals("1") ) out.print("selected");
      out.write(">아이디</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\" ");
 if( sch_mode.equals("2") ) out.print("selected");
      out.write(">이름</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\" ");
 if( sch_mode.equals("3") ) out.print("selected");
      out.write(">IP</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width:460px;vertical-align:middle\" class=\"textbox\" type=\"text\" name=\"sch_val\" value=\"");
      out.print(sch_val);
      out.write("\"><img src=\"../../../images/admin/log/btn_search.gif\" onclick=\"seach();\" style=\"cursor:pointer;vertical-align:middle\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"height:30px;\">검색 조건</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<table style=\"color:#2f5065;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"logKinds\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">전체</option>\r\n");

		for(int i=0;i<logKindsList.size();i++){	
			logBean = new LogBean();
			logBean = (LogBean)logKindsList.get(i);

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(logBean.getL_kinds());
      out.write('"');
      out.write(' ');
 if( logBean.getL_kinds().equals(logKinds) ) out.print("selected");
      out.write('>');
      out.print(logBean.getL_kindsName());
      out.write("</option>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"height:30px;\">로그 상세</th>\r\n");
      out.write("\t\t\t\t\t\t<td><select name=\"logType\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">전체</option>\r\n");

		for(int i=0;i<logTypeList.size();i++){	
			logBean = new LogBean();
			logBean = (LogBean)logTypeList.get(i);

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(logBean.getL_type());
      out.write('"');
      out.write(' ');
 if( logBean.getL_type().equals(logType) ) out.print("selected");
      out.write('>');
      out.print(logBean.getL_typeName());
      out.write("</option>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 검색 끝 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"height:45px; text-align: right\"><b>");
      out.print(logMgr.getListCnt());
      out.write("</b>건 , <b>");
      out.print(nowpage);
      out.write('/');
      out.print((logMgr.getListCnt()/PAGE_SIZE));
      out.write("</b>page</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 게시판 시작 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>       \r\n");
      out.write("\t\t\t\t<table id=\"board_01\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("\t\t\t\t<col width=\"20%\"><col width=\"20%\"><col width=\"20%\"><col width=\"20%\"><col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t<tr>    \r\n");
      out.write("\t\t\t\t\t\t<th>로그 종류</th>\r\n");
      out.write("\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t<th>IP</th>\r\n");
      out.write("\t\t\t\t\t\t<th>날짜</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");

	if(logList.size() > 0){
		for(int i = 0; i < logList.size(); i++){
			logBean = new LogBean();
			logBean = (LogBean)logList.get(i);

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(logBean.getL_kindsName()+"/"+logBean.getL_typeName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(logBean.getM_id());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(logBean.getM_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(logBean.getL_ip());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(logBean.getL_date());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");

		}
	}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"5\" style=\"font-weight:bold;height:40px\" align=\"center\">조건에 맞는 데이터가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 게시판 끝 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"height:40px;\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<table style=\"padding-top:10px;\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table id=\"paging\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(PageIndex.getPageIndex(nowpage, totpage,"","" ));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
