/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:39:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.admin.usergroup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import risk.util.*;
import java.util.List;
import risk.search.userEnvMgr;
import risk.search.keywordInfo;
import risk.admin.site.SitegroupBean;
import risk.admin.site.SiteMng;
import risk.admin.membergroup.membergroupBean;
import risk.admin.membergroup.membergroupMng;
import risk.issue.IssueCodeMgr;
import risk.issue.IssueCodeBean;
import java.util.ArrayList;
import risk.admin.usergroup.UserGroupMgr;
import risk.admin.usergroup.UserGroupSuperBean;
import risk.admin.usergroup.UserGroupSuperBean.MenuBean;
import risk.util.ConfigUtil;

public final class ifram_005fusergroup_005fright_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/admin/usergroup/../../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("risk.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.admin.site.SiteMng");
    _jspx_imports_classes.add("risk.issue.IssueCodeMgr");
    _jspx_imports_classes.add("risk.admin.usergroup.UserGroupSuperBean");
    _jspx_imports_classes.add("risk.admin.usergroup.UserGroupSuperBean.MenuBean");
    _jspx_imports_classes.add("risk.admin.membergroup.membergroupMng");
    _jspx_imports_classes.add("risk.admin.usergroup.UserGroupMgr");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.search.userEnvMgr");
    _jspx_imports_classes.add("risk.admin.site.SitegroupBean");
    _jspx_imports_classes.add("risk.issue.IssueCodeBean");
    _jspx_imports_classes.add("risk.search.keywordInfo");
    _jspx_imports_classes.add("risk.admin.membergroup.membergroupBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	int i;
	List KGlist = null;
	List sglist = null;
	String mgseq = null;
	String[] menufd = null;
	String[] companyfd = null;
	String[] xpfd = null;
	String[] sgfd = null;
	membergroupBean mginfo = null;

	StringUtil su = new StringUtil();
	userEnvMgr uemng = new userEnvMgr();
	KGlist = uemng.getKeywordGroup();

	SiteMng sitemng = new SiteMng();
	membergroupMng mgmng = membergroupMng.getInstance();

	if( request.getParameter("mgseq") != null ) {
		mgseq = request.getParameter("mgseq");
		mginfo = (membergroupBean)mgmng.getMGBean(mgseq);
		if( mginfo.getMGmenu() != null ) menufd = mginfo.getMGmenu().split(",");
		if( mginfo.getMGcompany() != null ) companyfd = mginfo.getMGcompany().split(",");
		if( mginfo.getMGxp() != null ) xpfd = mginfo.getMGxp().split(",");
		if( mginfo.getMGsite() != null ) sgfd = mginfo.getMGsite().split(",");
	}
	
	//IssueCodeMgr 인스턴스 생성
	IssueCodeMgr icMgr = new IssueCodeMgr();
	IssueCodeBean icBean = null;	
	ArrayList arrIcBean = null;
	arrIcBean = icMgr.GetTypeOrderName(7); 
	
	//메뉴 가져오기~~
	UserGroupMgr uMgr = new UserGroupMgr();
	ArrayList menuDataAll = uMgr.getMenu();
	ArrayList menuDataXp = uMgr.getDetalMenu(menuDataAll, "xp");
	//ArrayList menuDataYp = uMgr.getDetalMenu(menuDataAll, "yp");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../../css/base.css\" type=\"text/css\">\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction mnu_click(obj, index){\r\n");
      out.write("\r\n");
      out.write("\t\tvar table = document.getElementById('pop_mail_group');\r\n");
      out.write("\r\n");
      out.write("\t\tvar t = null;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\tfor(var i = 0; i < table.rows[0].cells.length; i++){\r\n");
      out.write("\r\n");
      out.write("\t\t\tt = document.getElementById('tabImg'+ (i+1));\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(i == 0){\r\n");
      out.write("\t\t\t\tt.innerHTML = '메뉴';\r\n");
      out.write("\t\t\t}else if(i == 1){\r\n");
      out.write("\t\t\t\tt.innerHTML = '키워드그룹';\r\n");
      out.write("\t\t\t}else if(i == 2){\r\n");
      out.write("\t\t\t\tt.innerHTML = '사이트그룹';\r\n");
      out.write("\t\t\t}else if(i == 3){\r\n");
      out.write("\t\t\t\tt.innerHTML = '계열사';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tt.className = 'tab_off';\r\n");
      out.write("\t\t\tdocument.getElementById('tab'+(i+1)).style.display = 'none';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tobj.className = 'tab_on';\r\n");
      out.write("\t\tif(index == 0){\r\n");
      out.write("\t\t\tobj.innerHTML = '<span class=\"tab_on_txt\">메 뉴</span>';\r\n");
      out.write("\t\t\tdocument.getElementById('tab'+(index+1)).style.display = '';\r\n");
      out.write("\t\t}else if(index == 1){\r\n");
      out.write("\t\t\tobj.innerHTML = '<span class=\"tab_on_txt\">키워드그룹</span>';\r\n");
      out.write("\t\t\tdocument.getElementById('tab'+(index+1)).style.display = '';\r\n");
      out.write("\t\t}else if(index == 2){\r\n");
      out.write("\t\t\tobj.innerHTML = '<span class=\"tab_on_txt\">사이트그룹</span>';\r\n");
      out.write("\t\t\tdocument.getElementById('tab'+(index+1)).style.display = '';\r\n");
      out.write("\t\t}else if(index == 3){\r\n");
      out.write("\t\t\tobj.innerHTML = '<span class=\"tab_on_txt\">계열사</span>';\r\n");
      out.write("\t\t\tdocument.getElementById('tab'+(index+1)).style.display = '';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction curr_save() {\r\n");
      out.write("\t\tif(confirm(\"변경 내용을 저장하시면 사용권한이 변경됩니다.\\n \"))\r\n");
      out.write("\t\t\tif( mgset.mgseq.value ) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar obj = document.mgset.mg_menu;\r\n");
      out.write("\t\t\t\tvar strIdx = \"\"; \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(obj.length){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < obj.length; i++){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif(obj[i].checked){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(strIdx == \"\"){\r\n");
      out.write("\t\t\t\t\t\t\t\tstrIdx = String(i);\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tstrIdx += \",\" + String(i); \r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tstrIdx = \"0\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t document.mgset.menuIdx.value = strIdx;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmgset.submit();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction allCheckMenu(){\r\n");
      out.write("\t\tvar obj = document.mgset.mg_menu;\r\n");
      out.write("\r\n");
      out.write("\t\tvar checked = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.mgset.mg_menu_all.checked){\r\n");
      out.write("\t\t\tchecked = true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tchecked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tvar obj2;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(i=0; i<obj.length ; i++){\r\n");
      out.write("\t\t\tobj[i].checked = checked;\r\n");
      out.write("\r\n");
      out.write("\t\t\tobj2 = document.getElementsByName(\"mg_menu2_\" + i);\r\n");
      out.write("\r\n");
      out.write("\t\t\t for(var j = 0; j < obj2.length; j++){\r\n");
      out.write("\t\t\t\t \t\t\t\t \r\n");
      out.write("\t\t\t\t obj2[j].checked = checked;\r\n");
      out.write("\t\t\t } \t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction allCheckSubMenu(pObj , idx){\r\n");
      out.write("\r\n");
      out.write("\t\tvar obj;\r\n");
      out.write("\t\tobj = document.getElementsByName(\"mg_menu2_\" + idx);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(obj){\r\n");
      out.write("\t\t\tif(obj.length){\r\n");
      out.write("\t\t\t\tfor(var i =0; i < obj.length; i++){\r\n");
      out.write("\t\t\t\t\tobj[i].checked = pObj.checked;\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tobj.checked = pObj.checked;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfunction checkMenu() {\r\n");
      out.write("\t\tvar obj = document.mgset.mg_menu;\r\n");
      out.write("\t\tvar count = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(i=0; i<obj.length ; i++){\r\n");
      out.write("\t\t\tif(obj[i].checked) count++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(obj.length == count){\r\n");
      out.write("\t\t\tdocument.mgset.mg_menu_all.checked = true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.mgset.mg_menu_all.checked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction allCheckCompany() {\r\n");
      out.write("\t\tvar obj = document.mgset.mg_company;\r\n");
      out.write("\r\n");
      out.write("\t\tvar checked = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.mgset.mg_company_all.checked){\r\n");
      out.write("\t\t\tchecked = true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tchecked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfor(i=0; i<obj.length ; i++){\r\n");
      out.write("\t\t\tobj[i].checked = checked;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkCompany() {\r\n");
      out.write("\t\tvar obj = document.mgset.mg_company;\r\n");
      out.write("\t\tvar count = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(i=0; i<obj.length ; i++){\r\n");
      out.write("\t\t\tif(obj[i].checked) count++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(obj.length == count){\r\n");
      out.write("\t\t\tdocument.mgset.mg_company_all.checked = true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.mgset.mg_company_all.checked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction allCheckKeyGroup() {\r\n");
      out.write("\t\tvar obj = document.mgset.mg_kg;\r\n");
      out.write("\r\n");
      out.write("\t\tvar checked = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.mgset.mg_kg_all.checked){\r\n");
      out.write("\t\t\tchecked = true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tchecked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfor(i=0; i<obj.length ; i++){\r\n");
      out.write("\t\t\tobj[i].checked = checked;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkKeyGroup() {\r\n");
      out.write("\t\tvar obj = document.mgset.mg_kg;\r\n");
      out.write("\t\tvar count = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(i=0; i<obj.length ; i++){\r\n");
      out.write("\t\t\tif(obj[i].checked) count++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(obj.length == count){\r\n");
      out.write("\t\t\tdocument.mgset.mg_kg_all.checked = true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.mgset.mg_kg_all.checked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction allCheckSite() {\r\n");
      out.write("\t\tvar obj = document.mgset.mg_site;\r\n");
      out.write("\r\n");
      out.write("\t\tvar checked = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.mgset.mg_site_all.checked){\r\n");
      out.write("\t\t\tchecked = true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tchecked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(i=0; i<obj.length ; i++){\r\n");
      out.write("\t\t\tobj[i].checked = checked;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction checkSite() {\r\n");
      out.write("\t\tvar obj = document.mgset.mg_site;\r\n");
      out.write("\t\tvar count = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(i=0; i<obj.length ; i++){\r\n");
      out.write("\t\t\tif(obj[i].checked) count++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(obj.length == count){\r\n");
      out.write("\t\t\tdocument.mgset.mg_site_all.checked = true;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.mgset.mg_site_all.checked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction visibleMenu(xp) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar trObj = document.getElementById(\"tr_menu_\" + xp);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(trObj.style.display == 'none'){\r\n");
      out.write("\t\t\ttrObj.style.display = '';\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\ttrObj.style.display = 'none';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"mgset\" action=\"ifram_usergroup_right_prc.jsp\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"mgseq\" value=\"");
      out.print(mgseq);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"menuIdx\" value= \"\">\r\n");
      out.write("<table id=\"pop_mail_group\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th style=\"width:25%; cursor: pointer;\" id=\"tabImg1\" class=\"tab_on\" onclick=\"mnu_click(this, 0)\"><span class=\"tab_on_txt\">메 뉴</span></th>\r\n");
      out.write("\t\t<th style=\"width:25%; cursor: pointer;\" class=\"tab_off\" id=\"tabImg2\"  onclick=\"mnu_click(this, 1)\">키워드그룹</th>\r\n");
      out.write("\t\t<th style=\"width:25%; cursor: pointer;\" class=\"tab_off\" id=\"tabImg3\"  onclick=\"mnu_click(this, 2)\">사이트그룹</th>\r\n");
      out.write("\t\t<!-- <th style=\"width:25%; cursor: pointer;\" class=\"tab_off\" id=\"tabImg4\"  onclick=\"mnu_click(this, 3)\">계열사</th> -->\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"tab1\" colspan=\"4\" style=\"padding:10px;\" valign=\"top\">\r\n");
      out.write("\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_menu_all\" onclick=\"allCheckMenu(");

      out.write(");\" ");
if( menufd != null )if(menufd.length == 6)out.println("checked");
      out.write("><strong>전체</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("<!--\t\t\t<tr>-->\r\n");
      out.write("<!--\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_menu\" value=\"6\" onclick=\"checkMenu();\" ");
if( menufd != null ){ if( su.inarray(menufd, "6") ) out.println("checked");}
      out.write(">대시보드</td>-->\r\n");
      out.write("<!--\t\t\t</tr>-->\r\n");
      out.write("<!--\t\t\t<tr>-->\r\n");
      out.write("<!--\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_menu\" value=\"1\" onclick=\"checkMenu();\" ");
if( menufd != null ){ if( su.inarray(menufd, "1") ) out.println("checked");}
      out.write(">정보검색</td>-->\r\n");
      out.write("<!--\t\t\t</tr>-->\r\n");
      out.write("<!--\t\t\t<tr>-->\r\n");
      out.write("<!--\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_menu\" value=\"2\" onclick=\"checkMenu();\" ");
if( menufd != null ){ if( su.inarray(menufd, "2") ) out.println("checked");}
      out.write(">이슈관리</td>-->\r\n");
      out.write("<!--\t\t\t</tr>-->\r\n");
      out.write("<!--\t\t\t<tr>-->\r\n");
      out.write("<!--\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_menu\" value=\"3\" onclick=\"checkMenu();\" ");
if( menufd != null ){ if( su.inarray(menufd, "3") ) out.println("checked");}
      out.write(">보고서관리</td>-->\r\n");
      out.write("<!--\t\t\t</tr>-->\r\n");
      out.write("<!--\t\t\t<tr>-->\r\n");
      out.write("<!--\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_menu\" value=\"4\" onclick=\"checkMenu();\" ");
if( menufd != null ){ if( su.inarray(menufd, "4") ) out.println("checked");}
      out.write(">통계분석</td>-->\r\n");
      out.write("<!--\t\t\t</tr>-->\r\n");
      out.write("<!--\t\t\t<tr>-->\r\n");
      out.write("<!--\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_menu\" value=\"5\" onclick=\"checkMenu();\" ");
if( menufd != null ){ if( su.inarray(menufd, "5") ) out.println("checked");}
      out.write(">관리자</td>-->\r\n");
      out.write("<!--\t\t\t</tr>-->\r\n");
      out.write("\r\n");
      out.write("<!--\t\t\t</tr>-->\r\n");

UserGroupSuperBean.MenuBean mb_bean = null;
UserGroupSuperBean.MenuBean mb_bean2 = null;
ArrayList detalData = null;
String checked = "";
	for( i=0 ; i < menuDataXp.size() ; i++ ) {
		mb_bean = (UserGroupSuperBean.MenuBean)menuDataXp.get(i);
		
		//System.out.println(mginfo.getMGmenu() + " / " + mb_bean.getMe_seq());
		checked = "";
		if( menufd != null ){ 
			if( su.inarray(menufd, mb_bean.getMe_seq())){
				checked = "checked";
			}
		}
		

      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_menu\"  onclick=\"allCheckSubMenu(this, '");
      out.print(i);
      out.write("');\" value=\"");
      out.print(mb_bean.getMe_seq());
      out.write('"');
      out.write(' ');
      out.print(checked);
      out.write("><span id=\"sp_menu1\" style=\"cursor: pointer;\" onclick=\"visibleMenu('");
      out.print(mb_bean.getMe_xp());
      out.write("')\">");
      out.print(mb_bean.getMe_name());
      out.write("</span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr id=\"tr_menu_");
      out.print(mb_bean.getMe_xp());
      out.write("\" style=\"display: ");
      out.print( checked.equals("") ? "none" : "");
      out.write(";\">\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<table  width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t");

				detalData = uMgr.getMenuYp(menuDataAll, mb_bean.getMe_xp());
				for(int j = 0; j <detalData.size(); j++){
					mb_bean2 = (UserGroupSuperBean.MenuBean)detalData.get(j);
			
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"pop_mail_group_td_on\">&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"checkbox\" name=\"mg_menu2_");
      out.print(i);
      out.write("\" id=\"mg_menu2_");
      out.print(i);
      out.write("\" value=\"");
      out.print(mb_bean2.getMe_seq());
      out.write('"');
      out.write(' ');
if( menufd != null ){ if( su.inarray(menufd, mb_bean2.getMe_seq()) ) out.println("checked");}
      out.write('>');
      out.print(mb_bean2.getMe_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");

	}

      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td id=\"tab2\" style=\"display:none;\" colspan=\"3\" style=\"padding:10px;\" valign=\"top\">\r\n");
      out.write("\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_kg_all\" onclick=\"allCheckKeyGroup();\" ");
if( xpfd != null ){if(xpfd.length == KGlist.size())out.println("checked");}
      out.write("><strong>전체</strong></td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");

	for( i=0 ; i < KGlist.size() ; i++ ) {
		keywordInfo KGset = (keywordInfo)KGlist.get(i);

      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_kg\" onclick=\"checkKeyGroup();\" value=\"");
      out.print(KGset.getK_Xp());
      out.write('"');
      out.write(' ');
if( xpfd != null ){ if( su.inarray(xpfd, KGset.getK_Xp()) ) out.println("checked");}
      out.write('>');
      out.print(KGset.getK_Value());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");

	}

	sglist = sitemng.getSGList();

      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td id=\"tab3\" style=\"display:none;\" colspan=\"3\" style=\"padding:10px;\" valign=\"top\">\r\n");
      out.write("\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_site_all\" onclick=\"allCheckSite();\" ");
if( sgfd != null ){if(sgfd.length == sglist.size())out.println("checked");}
      out.write("><strong>전체</strong></td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");

	for( i=0 ; i < sglist.size() ; i++ ) {
		SitegroupBean SGinfo = (SitegroupBean)sglist.get(i);

      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_site\" onclick=\"checkSite();\" value=\"");
      out.print(SGinfo.get_seq());
      out.write('"');
      out.write(' ');
if( sgfd != null ){ if( su.inarray(sgfd, String.valueOf(SGinfo.get_seq())) ) out.println("checked");}
      out.write('>');
      out.print( SGinfo.get_name());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td id=\"tab4\" style=\"display:none;\" colspan=\"3\" style=\"padding:10px;\" valign=\"top\">\r\n");
      out.write("\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pop_mail_group_td\"><input type=\"checkbox\" name=\"mg_company_all\" onclick=\"allCheckCompany();\" ");
if( companyfd != null ){if(companyfd.length == arrIcBean.size()-1)out.println("checked");}
      out.write("><strong>전체</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");

	for( i = 0; i < arrIcBean.size(); i++){
	icBean = (IssueCodeBean) arrIcBean.get(i);
	
	String bgcolor = "";
	if(icBean.getIc_ptype() == 4 && icBean.getIc_pcode() == 3) 
		bgcolor = "bgcolor=\"#eeeeee\"";
	else
		bgcolor = "bgcolor=\"#ffffff\"";

      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"pop_mail_group_td\" ");
      out.print(bgcolor );
      out.write("><input type=\"checkbox\" name=\"mg_company\" onclick=\"checkCompany();\" value=\"");
      out.print(icBean.getIc_code());
      out.write('"');
      out.write(' ');
if( companyfd != null ){ if( su.inarray(companyfd, Integer.toString(icBean.getIc_code())) ) out.println("checked");}
      out.write('>');
      out.print( icBean.getIc_name());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
