/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:39:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.admin.warning_005fkeyword;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import risk.util.ConfigUtil;

public final class admin_005fkeyword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/admin/warning_keyword/../../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.util.ConfigUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../../css/base.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tfunction add_key()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tfrm = keyword_right.keygroup;\r\n");
      out.write("\t\tfrm.mode.value = 'add';\r\n");
      out.write("\t\tvar url = \"pop_keyword_add.jsp?xp=\"+frm.xp.value+\"&yp=\"+frm.yp.value+\"&zp=\"+frm.zp.value;\r\n");
      out.write("\t\twindow.open(url, \"pop_keyword\", \"width=400,height=300\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction del_key()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif( confirm(\"하위분류 및 키워드까지 삭제됩니다.\\n삭제하시겠습니까?\") )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tkeyword_right.del_kg();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction up_key()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tkeyword_right.up_kg();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction down_key()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tkeyword_right.down_kg();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction keySave()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.frm_keyword_get.location = 'keyword_download_excel.jsp';\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction openLayer()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"floater\").style.display='';\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeLayer()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"floater\").style.display='none';\r\n");
      out.write("\t}\r\n");
      out.write("\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin-left: 15px\">\r\n");
      out.write("<div id=\"floater\" style=\"width:328px;height:168px; top:485px; left:490px; cellspacing:0; cellpadding:0; position: absolute;border:black 0px solid; display:none;\">  \r\n");
      out.write("<img src=\"../../../images/admin/warning/layer_img.gif\" style=\"cursor:hand\" onclick=\"closeLayer();\"></img>\r\n");
      out.write("</div>\r\n");
      out.write("<table style=\"width:100%;height:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"body_bg_top\" valign=\"top\">\r\n");
      out.write("\t\t\t<table width=\"820\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"tit_bg\" style=\"height:67px;padding-top:20px;\">\r\n");
      out.write("\t\t\t\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><img src=\"../../../images/admin/warning/tit_icon.gif\" /><img src=\"../../../images/admin/warning/tit_0529.gif\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"navi_home\">HOME</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"navi_arrow\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"navi_arrow2\">워닝키워드관리</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td height=\"15\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("      <table width=\"770\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td align=\"right\" style=\"padding-left:10px\"><table width=\"750\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"35\" align=\"left\">수집된 정보의 필터링 및 분류에 사용될 키워드 그룹 및 키워드를 관리합니다.</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("             <tr>\r\n");
      out.write("              <td height=\"10\">&nbsp;</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("            <table width=\"750\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("\t\t\t    <td align=\"left\">&nbsp;</td>\r\n");
      out.write("                <td width=\"220\" align=\"left\" valign=\"top\"><table width=\"220\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td height=\"25\" class=\"textBbig\" >\r\n");
      out.write("                    \t<table width=\"100%\" border=\"0\">\r\n");
      out.write("                    \t\t<tr>\r\n");
      out.write("                    \t\t\t<td align=\"left\"><img src=\"../../../images/admin/warning/admin_ico01.gif\" width=\"12\" height=\"10\" hspace=\"2\"><strong>키워드그룹</strong></td>\r\n");
      out.write("                    \t\t\t<td align=\"right\"><img src=\"../../../images/admin/warning/excel_save.gif\" width=\"94\" height=\"24\" hspace=\"2\" onclick=\"keySave();\" style=\"cursor:hand;\"></td>\r\n");
      out.write("                    \t\t</tr>\r\n");
      out.write("                    \t</table>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><iframe name=\"keyword_left\" id=\"keyword_left\" src=\"admin_keyword_left.jsp\" width=\"240\" height=\"300\" scrolling=\"auto\" frameborder=\"0\" style=\"border:1px solid; border-color:#CCCCCC\"></iframe></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                  <table width=\"240\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td><img src=\"../../../images/admin/warning/form_add.gif\" vspace=\"5\" OnKeyDown=\"Javascript:if (event.keyCode == 13) { add_key();}\" onclick=\"add_key();\" style=\"cursor:hand;\"><img src=\"../../../images/admin/warning/form_del.gif\" hspace=\"5\" vspace=\"5\" onclick=\"del_key();\" style=\"cursor:hand;\"></td>\r\n");
      out.write("                      <td align=\"right\"><img src=\"../../../images/admin/warning/up_btn.gif\" width=\"18\" height=\"18\" onclick=\"up_key();\" style=\"cursor:hand;\"><img src=\"../../../images/admin/warning/down_btn.gif\" width=\"18\" height=\"18\" hspace=\"5\" onclick=\"down_key();\" style=\"cursor:hand;\"></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table></td>\r\n");
      out.write("                <td width=\"30\" align=\"left\">&nbsp;</td>\r\n");
      out.write("                <td width=\"335\" align=\"left\" valign=\"top\"><table width=\"335\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td height=\"25\" align=\"left\" class=\"textBbig\" ><img src=\"../../../images/admin/warning/admin_ico01.gif\" width=\"12\" height=\"10\" hspace=\"2\"><strong>세부정보</strong></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><iframe name=\"keyword_right\" id=\"keyword_right\" src=\"admin_keyword_right.jsp\" width=\"335\" height=\"300\" scrolling=\"auto\" frameborder=\"0\" style=\"border:1px solid; border-color:#CCCCCC\"></iframe></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("\t\t          \t<td height=\"10\" align=\"right\">&nbsp;</td>\r\n");
      out.write("\t\t          </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("\t\t          \t<td height=\"10\" align=\"right\"><img src=\"../../../images/admin/warning/banner_01.gif\" style=\"cursor:hand\" onclick=\"openLayer();\"></td>\r\n");
      out.write("\t\t          </tr>\r\n");
      out.write("                </table>                  \r\n");
      out.write("                  <table width=\"335\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td align=\"right\"><!--<img src=\"../../../images/admin/warning/btn_save.gif\" width=\"48\" height=\"21\" vspace=\"5\">--></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table></td>\r\n");
      out.write("                <td align=\"left\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<iframe name=\"frm_keyword_get\" id=\"frm_keyword_get\" src=\"\" width=\"0\" height=\"0\" frameborder=\"0\"></iframe>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
