/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:39:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.admin.alimi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import risk.util.ConfigUtil;
import risk.mobile.AlimiSettingDao;
import risk.mobile.AlimiSettingBean;
import risk.admin.alimi.AlimiLogMgr;
import risk.admin.alimi.AlimiLogSuperBean;
import risk.util.ParseRequest;
import java.util.ArrayList;
import java.util.*;
import risk.util.PageIndex;

public final class alimi_005fsetting_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/admin/alimi/../../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.util.PageIndex");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.admin.alimi.AlimiLogSuperBean");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("risk.mobile.AlimiSettingDao");
    _jspx_imports_classes.add("risk.admin.alimi.AlimiLogMgr");
    _jspx_imports_classes.add("risk.mobile.AlimiSettingBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	ParseRequest pr = new ParseRequest(request);
	AlimiSettingDao asDao = new AlimiSettingDao();
	AlimiSettingBean asBean = new AlimiSettingBean();
	ArrayList arrAlimiSetList = new ArrayList();
	
	pr.printParams();
	
	int rowCnt = 10;
	int iNowPage  = pr.getInt("nowpage",1);	
	
	//arrAlimiSetList = asDao.getAlimiSetList(iNowPage , rowCnt ,"","Y");
	arrAlimiSetList = asDao.getTelegramSetList(iNowPage , rowCnt ,"","");
	
	int iTotalCnt= asDao.getListCnt();	
	int iTotalPage      = iTotalCnt / rowCnt;
    if ( ( iTotalCnt % rowCnt ) > 0 ) iTotalPage++;
    
	AlimiLogMgr lMgr = new AlimiLogMgr();
	
	//ArrayList reData = lMgr.getAlimiLogList(iNowPage , rowCnt, sDateFrom, sDateTo, mal_type, searchKey, as_type);
	//ArrayList reData = lMgr.getTelegramLogList(iNowPage , rowCnt, sDateFrom, sDateTo, mal_type, searchKey, tl_code);


	

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>RISK</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../css/base.css\" />\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tvar allcheck = 0;\r\n");
      out.write("\r\n");
      out.write("\tfunction asSetInsert()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.alimi_setting_list;\r\n");
      out.write("\t\tf.mode.value='INSERT';\r\n");
      out.write("\t\tf.target='';\r\n");
      out.write("\t\tf.action = 'alimi_setting_detail.jsp';\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction asSetUpdate( ts_seq )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.alimi_setting_list;\r\n");
      out.write("\t\tf.ts_seq.value = ts_seq;\r\n");
      out.write("\t\tf.mode.value ='UPDATE';\r\n");
      out.write("\t\tf.target='';\r\n");
      out.write("\t\tf.action = 'alimi_setting_detail.jsp';\r\n");
      out.write("\t\tf.submit();\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction allselect()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar frm = document.all;\r\n");
      out.write("\t\tif( frm.chkNum ) {\r\n");
      out.write("\t\t\tif( allcheck == 0 ) {\r\n");
      out.write("\t\t\t\tif( frm.chkNum.length > 1 ) {\r\n");
      out.write("\t\t\t\t\tfor( i=0; i< frm.chkNum.length; i++ )\r\n");
      out.write("\t\t\t   \t\t{\r\n");
      out.write("\t\t\t   \t\t\t frm.chkNum[i].checked = true;\r\n");
      out.write("\t\t\t   \t\t}\r\n");
      out.write("\t\t\t   \t}else {\r\n");
      out.write("\t\t\t   \t\tfrm.chkNum.checked = true;\r\n");
      out.write("\t\t\t   \t}\r\n");
      out.write("\t\t   \t\tallcheck = 1;\r\n");
      out.write("\t\t   \t}else {\r\n");
      out.write("\t\t   \t\tif( frm.chkNum.length > 1 ) {\r\n");
      out.write("\t\t\t   \t\tfor( i=0; i< frm.chkNum.length; i++ )\r\n");
      out.write("\t\t\t   \t\t{\r\n");
      out.write("\t\t\t   \t\t\t frm.chkNum[i].checked = false;\r\n");
      out.write("\t\t\t   \t\t}\r\n");
      out.write("\t\t\t   \t}else {\r\n");
      out.write("\t\t\t   \t\tfrm.chkNum.checked = false;\r\n");
      out.write("\t\t\t   \t}\r\n");
      out.write("\t\t   \t\tallcheck = 0;\r\n");
      out.write("\t\t   \t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction delList()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar selectNum = '';\r\n");
      out.write("    \tvar i = 0;\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar frm = document.alimi_setting_list;\r\n");
      out.write("    \t\r\n");
      out.write("    \tif ( confirm(\"삭제 하시겠습니까?\" ) ) {\r\n");
      out.write("    \t\tif( frm.chkNum ) {\r\n");
      out.write("\t    \t\tif( frm.chkNum.length > 1 ) {\r\n");
      out.write("\t\t    \t\tfor( i=0; i< frm.chkNum.length; i++ )\r\n");
      out.write("\t\t    \t\t{\r\n");
      out.write("\t\t    \t\t\tif( frm.chkNum[i].checked == true ) {\r\n");
      out.write("\t\t    \t\t\t\tif( selectNum.length > 0 ) {\r\n");
      out.write("\t\t    \t\t\t\t\tselectNum = selectNum+','+frm.chkNum[i].value;\r\n");
      out.write("\t\t    \t\t\t\t}else {\r\n");
      out.write("\t\t    \t\t\t\t\tselectNum = frm.chkNum[i].value;\r\n");
      out.write("\t\t    \t\t\t\t}\r\n");
      out.write("\t\t    \t\t\t}\r\n");
      out.write("\t\t    \t\t}\r\n");
      out.write("\t\t    \t}else {\r\n");
      out.write("\t\t    \t\tif( frm.chkNum.checked == true ) {\r\n");
      out.write("\t\t    \t\t\tselectNum = frm.chkNum.value;\r\n");
      out.write("\t\t    \t\t}\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//alert(selectNum);\r\n");
      out.write("\t\t    if( selectNum.length > 0 ) {\r\n");
      out.write("\t\t\t    frm.ts_seqs.value = selectNum;\r\n");
      out.write("\t\t\t    frm.mode.value = 'DELETE';\r\n");
      out.write("\t\t\t    frm.target = '';\r\n");
      out.write("\t\t\t    frm.action = 'alimi_setting_prc.jsp';\r\n");
      out.write("\t\t\t    frm.submit();\r\n");
      out.write("\t\t\t}else {\r\n");
      out.write("\t    \t\talert('삭제할 수신자를 선택하세요');\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction pageClick( paramUrl ) {\r\n");
      out.write("\t\tvar f = document.alimi_setting_list;\r\n");
      out.write("\t\tf.nowpage.value = paramUrl.substr(paramUrl.indexOf(\"=\")+1, paramUrl.length);\r\n");
      out.write("\t\tf.action='alimi_setting_list.jsp';\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin-left: 15px\">\r\n");
      out.write("<form name=\"alimi_setting_list\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"mode\">\r\n");
      out.write("<input type=\"hidden\" name=\"nowpage\" value=\"");
      out.print(iNowPage);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"ts_seq\">\r\n");
      out.write("<input type=\"hidden\" name=\"ts_seqs\">\r\n");
      out.write("<table style=\"width:100%;height:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"body_bg_top\" valign=\"top\">\r\n");
      out.write("\t\t<table style=\"width:820px;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<!-- 타이틀 시작 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"tit_bg\" style=\"height:67px;padding-top:20px;\">\r\n");
      out.write("\t\t\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"../../../images/admin/alimi/tit_icon.gif\" /><img src=\"../../../images/admin/alimi/tit_0510.gif\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"navi_home\">HOME</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"navi_arrow\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"navi_arrow2\">텔레그램 알리미 설정관리</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td height=\"15\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 타이틀 끝 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"height:40px;\">\r\n");
      out.write("\t\t\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t  \t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:80px;\"><img src=\"../../../images/admin/alimi/btn_allselect.gif\" onclick=\"allselect();\" style=\"cursor:pointer;\"/></td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <td><img src=\"../../../images/admin/alimi/btn_del.gif\" onclick=\"delList();\" style=\"cursor:pointer;\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:52px;\"><img src=\"../../../images/admin/alimi/btn_alrimiadd.gif\" onclick=\"asSetInsert();\" style=\"cursor:pointer;\"/></td> -->\r\n");
      out.write("\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 게시판 시작 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>       \r\n");
      out.write("\t\t\t\t<table id=\"board_01\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("\t\t\t\t<col width=\"5%\"><col width=\"25%\"><col width=\"20%\"><col width=\"25%\"><col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t<tr>           \r\n");
      out.write("\t\t\t\t\t\t<th><input type=\"checkbox\" name=\"chkNum\" value=\"\" onclick=\"allselect();\"></th>  \r\n");
      out.write("\t\t\t\t\t\t<th>그룹방 명</th>\r\n");
      out.write("\t\t\t\t\t\t<th>작동 여부</th>\r\n");
      out.write("\t\t\t\t\t\t<th>ID 명</th>\r\n");
      out.write("\t\t\t\t\t\t<th>마지막 발송 일자</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");

	
	if(arrAlimiSetList.size()>0){
	  	for(int i=0; i < arrAlimiSetList.size(); i++)
		{
	  		asBean = new AlimiSettingBean();  	
	  		asBean = 	(AlimiSettingBean)arrAlimiSetList.get(i);

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"chkNum\" value=\"");
      out.print(asBean.getTs_seq());
      out.write("\"></td>  \r\n");
      out.write("\t\t\t\t\t\t<td onclick=\"asSetUpdate( '");
      out.print(asBean.getTs_seq());
      out.write("' );\" style=\"cursor:pointer\" ><p class=\"board_01_tit\">");
      out.print(asBean.getTs_name());
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t\t\t");
if(asBean.getOperate_yn().equals("0")){
      out.write("<td> N </td>");
}else if(!asBean.getOperate_yn().equals("0")){
      out.write("<td> Y </td>");
}
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(asBean.getTs_id());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(asBean.getLast_send_date());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");

		}
	}else{

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"6\" style=\"font-weight:bold;height:40px\" align=\"center\">조건에 맞는 데이터가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
		
	}

      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 게시판 끝 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"height:40px;\" align=\"center\">\r\n");
      out.write("\t\t\t\t<table style=\"padding-top:10px;\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"paging\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(PageIndex.getPageIndex(iNowPage, iTotalPage,"","" ));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
