/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:39:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.inc.topmenu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import risk.util.StringUtil;
import risk.search.userEnvInfo;
import risk.util.ParseRequest;
import risk.util.ConfigUtil;

public final class inc_005ftopmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/inc/topmenu/../sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.search.userEnvInfo");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("risk.util.StringUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');


	ParseRequest    pr = new ParseRequest(request);
	
	String sms = "";
	if( request.getParameter("sms") != null ) sms = request.getParameter("sms");
	
	pr.printParams();
	String selectedMenu =  pr.getString("selectedMenu","");
	
	

	String MGmenu = "";
	String[] arrMGmenu = null;

	StringUtil su = new StringUtil();

	userEnvInfo env = (userEnvInfo)session.getAttribute("ENV");
	MGmenu = env.getMg_menu();
	if( MGmenu != null )
	arrMGmenu = MGmenu.split(",");
	
	//대쉬보드 시간 초기화
	session.setAttribute("SS_SEARCHDATE", "");
	
	String firstMenu = arrMGmenu[0];

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../../css/top/base.css\" type=\"text/css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("\r\n");
      out.write("// 현재 선택된 메뉴를 저장한다.\r\n");
      out.write("// 초기에 지정해 주어야 한다. 지정하지 않으면 검색메뉴를 지정한다.\r\n");
      out.write("var selectedObj = \"\";\r\n");
      out.write("\r\n");
      out.write("// 각 메뉴 클릭시 이동할 페이지 정보를 지정한다.\r\n");
      out.write("var link = new Array(\r\n");
      out.write("// +Dashboard\r\n");
      out.write("\"../../search/search.jsp?INIT=INIT\",\r\n");
      out.write("\"../../issue/issue.jsp\",\r\n");
      out.write("\"../../report/report.jsp\",\r\n");
      out.write("\"../../statistics/statistics.jsp\",\r\n");
      out.write("\"../../admin/admin_main.jsp\"\r\n");
      out.write(");\r\n");
      out.write("// 메뉴 클릭시 이벤트\r\n");
      out.write("// 클릭한 메뉴를 선택상태로 만들고, 하단 프레임을 변경한다.\r\n");
      out.write("function mnu_chick(obj,seq) {\r\n");
      out.write("\tvar tmpObj;\r\n");
      out.write("\tfor (var i=1;i<7 ;i++ )\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttmpObj = document.getElementById('img'+i);\r\n");
      out.write("\t\tif( tmpObj ){\r\n");
      out.write("\t\t\tsetOff(tmpObj);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tsetOn(obj);\r\n");
      out.write("\tselectedObj = obj;\r\n");
      out.write("\tparent.bottomFrame.location.href=link[seq];\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function dashboard_chick() {\r\n");
      out.write("\t//parent.location.href = '../../../dashboard/index.jsp';\r\n");
      out.write("\tparent.location.href = '../../../dashboard/view/summary/index.jsp';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 각 메뉴의 마우스 오버시 이벤트\r\n");
      out.write("function mnu_over(obj) {\r\n");
      out.write("\tsetOn(obj);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 각 메뉴의 마우스 아웃시 이벤트\r\n");
      out.write("// 현재 선택된 메뉴면 \r\n");
      out.write("function mnu_out(obj) {\r\n");
      out.write("\tif (selectedObj != obj)\t{ setOff(obj);\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setOn(obj)\r\n");
      out.write("{\r\n");
      out.write("\tvar oSrc = obj.src;\r\n");
      out.write("\tre = /_off./i;\r\n");
      out.write("\tvar nSrc = obj.src.replace(re, \"_on.\");\r\n");
      out.write("\tobj.src=nSrc;\r\n");
      out.write("}\r\n");
      out.write("function setOff(obj)\r\n");
      out.write("{\r\n");
      out.write("\tvar oSrc = obj.src;\r\n");
      out.write("\tre = /_on./i;\r\n");
      out.write("\tvar nSrc = obj.src.replace(re, \"_off.\");\r\n");
      out.write("\tobj.src=nSrc;\r\n");
      out.write("}\r\n");
      out.write("function system_wait() {\r\n");
      out.write("\talert('준비중입니다.');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sms_check() {\r\n");
      out.write("\tsetOn(document.all.img3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pop_up(){\r\n");
      out.write("\tvar url =\"../../statistics_pop/index.jsp\"; \r\n");
      out.write("\twindow.open(url,\"search\",\"width=1200,height=1000,toolbar=no,status=no,location=no,scrollbars=yes,menubar=no,resizable=yes,left=50,right=50\");\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"62\" valign=\"top\" background=\"../../../images/top/top_bg.gif\"><table width=\"1000\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"200\"><img src=\"../../../images/top/system_logo.gif\" onclick=\"mnu_chick(img1, 0);\" width=\"200\" style=\"cursor: pointer;\"></td>\r\n");
      out.write("        <td width=\"808\" rowspan=\"2\" valign=\"top\" background=\"../../../images/top/top_bg_01.gif\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"10\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"52\" background=\"../../../images/top/top_bg_02.gif\"><table width=\"809\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("              ");

              	if( arrMGmenu != null ) {
              		if( su.inarray(arrMGmenu, "6") ) {
              
      out.write("\r\n");
      out.write("\t                <td width=\"94\"><img src=\"../../../images/top/menu_09_off.gif\" onclick=\"dashboard_chick();\" onMouseOut=\"mnu_out(this);\" onMouseOver=\"mnu_over(this);\" style=\"cursor: pointer;\" name=\"img6\" id=\"img6\"></td>\r\n");
      out.write("\t                <td width=\"1\"><img src=\"../../../images/top/menu_line.gif\" width=\"1\" height=\"52\" /></td>\r\n");
      out.write("\t\t\t\t");
	} 
              		if( su.inarray(arrMGmenu, "1") ) {
              	
      out.write("\r\n");
      out.write("\t                <td width=\"104\"><img src=\"../../../images/top/menu_01_off.gif\" onclick=\"mnu_chick(this, 0);\" onMouseOut=\"mnu_out(this);\" onMouseOver=\"mnu_over(this);\" style=\"cursor: pointer;\" name=\"img1\" id=\"img1\"></td>\r\n");
      out.write("\t                <td width=\"1\"><img src=\"../../../images/top/menu_line.gif\" width=\"1\" height=\"52\" /></td>\r\n");
      out.write("\t          \t");
	} 

              		if( su.inarray(arrMGmenu, "2") ) {
              
      out.write("      \r\n");
      out.write("\t                <td width=\"95\"><img src=\"../../../images/top/menu_02_off.gif\" onclick=\"mnu_chick(this, 1);\" onMouseOut=\"mnu_out(this);\" onMouseOver=\"mnu_over(this);\" style=\"cursor: pointer;\" name=\"img2\" id=\"img2\"></td>\r\n");
      out.write("\t                <td width=\"1\"><img src=\"../../../images/top/menu_line.gif\" width=\"1\" height=\"52\" /></td>\r\n");
      out.write("\t\t\t\t");
	} 

              		if( su.inarray(arrMGmenu, "3") ) {
              
      out.write("\r\n");
      out.write("\t                <td width=\"104\"><img src=\"../../../images/top/menu_03_off.gif\" onclick=\"mnu_chick(this, 2);\" onMouseOut=\"mnu_out(this);\" onMouseOver=\"mnu_over(this);\" style=\"cursor: pointer;\" name=\"img3\" id=\"img3\"></td>\r\n");
      out.write("\t                <td width=\"1\"><img src=\"../../../images/top/menu_line.gif\" width=\"1\" height=\"52\" /></td>\r\n");
      out.write("\t\t\t\t");
	} 

              		if( su.inarray(arrMGmenu, "4") ) {
              
      out.write("\r\n");
      out.write("\t                <!-- <td width=\"96\"><img src=\"../../../images/top/menu_04_off.gif\" onclick=\"mnu_chick(this, 3);\" onMouseOut=\"mnu_out(this);\" onMouseOver=\"mnu_over(this);\" style=\"cursor: pointer;\" name=\"img4\" id=\"img4\"></td> -->\r\n");
      out.write("\t                <td width=\"96\"><img src=\"../../../images/top/menu_04_off.gif\" onclick=\"pop_up();\" onMouseOut=\"mnu_out(this);\" onMouseOver=\"mnu_over(this);\" style=\"cursor: pointer;\" name=\"img4\" id=\"img4\"></td>\r\n");
      out.write("\t                <td width=\"1\"><img src=\"../../../images/top/menu_line.gif\" width=\"1\" height=\"52\" /></td>\r\n");
      out.write("\t\t\t\t");
	} 

              		if( su.inarray(arrMGmenu, "5") ) {
              			
              
      out.write("\r\n");
      out.write("\t                <td width=\"93\"><img src=\"../../../images/top/menu_06_off.gif\" onclick=\"mnu_chick(this, 4);\" onMouseOut=\"mnu_out(this);\" onMouseOver=\"mnu_over(this);\" style=\"cursor: pointer;\" name=\"img5\" id=\"img5\"></td>\r\n");
      out.write("\t                <td width=\"1\"><img src=\"../../../images/top/menu_line.gif\" width=\"1\" height=\"52\" /></td>\r\n");
      out.write("\t\t\t\t");
	}
              		
				}
      out.write(" \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <td width=\"95%\" valign=\"top\" background=\"../../../images/top/top_bg_03.gif\" style=\"padding:12px 0px 0px 0px\"><table width=\"230\" border=\"0\" align=\"right\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td width=\"140\"><img src=\"../../../images/top/login_icon.gif\" width=\"21\" height=\"13\" /><span class=\"gray_s_01\">");
      out.print(SS_M_NAME);
      out.write("님 반갑습니다.</span></td>\r\n");
      out.write("                      <td width=\"70\"><table width=\"68\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td width=\"34\"><a href=\"../../logout.jsp\" target=\"_top\"><img src=\"../../../images/top/login_icon_01.gif\" width=\"34\" height=\"24\"></a></td>\r\n");
      out.write("                            <td width=\"34\"><a href=\"../../search/search_env_setting.jsp\" target=\"contentsFrame\"><img src=\"../../../images/top/login_icon_02.gif\" width=\"34\" height=\"24\"></a></td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                      </table></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("                \r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          \r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td height=\"11\" valign=\"top\"><img src=\"../../../images/top/left_menu_bg.gif\" width=\"200\" height=\"11\" /></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("<SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("// 최초 선택된 메뉴를 선택상태로 만든다.\r\n");
      out.write("// 선택된 메뉴가 없으면 검색메뉴를 선택상태로 만든다.\r\n");
      out.write("//if (selectedObj==\"\"){selectedObj=document.getElementById('img'+");
//selectMenu
      out.write("//);  setOn(selectedObj);}\r\n");
      out.write("//else{setOn(selectedObj);}\r\n");
      out.write("\r\n");

	if(selectedMenu.equals("")){

      out.write("\r\n");
      out.write("\t\tif(eval(");
      out.print(firstMenu);
      out.write("+\" == '1' || \"+");
      out.print(firstMenu);
      out.write("+\" == '6'\")){\t\t\t\r\n");
      out.write("\t\t\tselectedObj=document.getElementById('img1');\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tselectedObj=document.getElementById('img'+");
      out.print(firstMenu);
      out.write(");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tsetOn(selectedObj);\r\n");
      out.write("\r\n");
		
	} else {

      out.write("\t\t\r\n");
      out.write("\tselectedObj=document.getElementById('img'+");
      out.print(selectedMenu);
      out.write(");\r\n");
      out.write("\tsetOn(selectedObj);\r\n");
		
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("function logOut(){\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</SCRIPT>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
