/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:41:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.admin.ex_005fsite;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import risk.util.ParseRequest;
import java.net.*;
import risk.util.PageIndex;
import risk.util.ConfigUtil;

public final class admin_005fex_005fsite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/admin/ex_site/../../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.util.PageIndex");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	System.out.println("■-------------admin_ex_site.jsp----------------■");
	ParseRequest    pr = new ParseRequest(request);
	pr.printParams();
	String searchKey = pr.getString("searchKey");			//검색어
	String order = pr.getString("order", "EK_KEYWORD ASC");	//정렬 순서
	
	/* //paging 처리
	int totpage = 0;
	int nowpage = 1;
	int count = 0;
	try {
		if (request.getParameter("nowpage") != null)
			nowpage = Integer.parseInt(request.getParameter("nowpage"));
	}catch (Exception e) {
		System.out.println("[admin_user_list] error1 : " + e);
	}
	
	try {
		count = dao.totalct;
		if (count > 0) {
			totpage = count / 10;

			if ((count % 10) > 0)
				totpage++;

		}
	} catch (Exception e) {
		System.out.println("error2 : " + e);
	} */
	

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>RIS-K</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../css/base.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(SS_URL);
      out.write("/css/common.css\" type=\"text/css\">\r\n");
      out.write("<script src=\"../../../js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../../../js/ajax.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../../../js/popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(loadList);\r\n");
      out.write("\t\r\n");
      out.write("\t//첨 로드시~\r\n");
      out.write("\tfunction loadList()\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\tajax.post('behind_ex_site_list.jsp?subCodeName=issueCode','managerForm','behindExSiteList');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//단어 검색시\r\n");
      out.write("\tfunction Search()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.managerForm;\r\n");
      out.write("\t\t//AJAX 사용시 한글처리\r\n");
      out.write("\t\t//f.searchKey.value = encodeURI(f.searchWord.value);\r\n");
      out.write("\t\t//앞뒤 공백 제거\r\n");
      out.write("\t\tf.searchWord.value = f.searchWord.value.replace(/^\\s*/,'');\r\n");
      out.write("\t\tf.searchWord.value = f.searchWord.value.replace(/\\s*$/,'');\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tloadList();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//정렬시\r\n");
      out.write("\tfunction excuteOrder(order)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.managerForm;\t\t\r\n");
      out.write("\t\tf.order.value = order;\t\t\r\n");
      out.write("\t\tSearch(); \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//성향단어 에디터팝\r\n");
      out.write("\tfunction popupEdit(id,mode)\r\n");
      out.write("\t{\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar f = document.managerForm;\t\t\r\n");
      out.write("\t\tf.ekSeq.value = id;\r\n");
      out.write("\t\tf.mode.value = mode;\r\n");
      out.write("\t\tif(mode=='update')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tpopup.openByPost('managerForm','admin_ex_site_edit.jsp',400,300,false,false,false,'trendPop');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tpopup.openByPost('managerForm','admin_ex_site_edit.jsp',400,300,false,false,false,'trendPop');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//체크 박스 전체 선택시\r\n");
      out.write("\tfunction selectAll(result)\r\n");
      out.write("\t{\t\t\t\r\n");
      out.write("\t\tvar f = document.managerForm;\r\n");
      out.write("\t\tif( f.checkId ) {\r\n");
      out.write("\t\t\tif(f.checkId.length){\r\n");
      out.write("\t\t\t\tfor(var i=0; i< f.checkId.length; i++ )\r\n");
      out.write("\t\t   \t\t{\r\n");
      out.write("\t\t   \t\t\t f.checkId[i].checked = result;\r\n");
      out.write("\t\t   \t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tf.checkId.checked = result;\r\n");
      out.write("\t\t\t}\t \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tf.checkAll.checked = result;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//체크된  ID\r\n");
      out.write("\tfunction checkId()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.managerForm;\r\n");
      out.write("\t\tf.checkIds.value = '';\r\n");
      out.write("\t\tif( f.checkId ) {\r\n");
      out.write("\t\t\tif(f.checkId.length){\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i=0; i< f.checkId.length; i++ )\r\n");
      out.write("\t\t   \t\t{\r\n");
      out.write("\t\t\t   \t\tif(f.checkId[i].checked==true)\r\n");
      out.write("\t\t\t   \t\t{\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t   \t\tf.checkIds.value == '' ? f.checkIds.value = f.checkId[i].value : f.checkIds.value += ','+ f.checkId[i].value;\r\n");
      out.write("\t\t\t   \t\t}\r\n");
      out.write("\t\t   \t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tif(f.checkId.checked==true)\r\n");
      out.write("\t\t   \t\t{\t\r\n");
      out.write("\t\t\t\t\tf.checkIds.value = f.checkId.value; \r\n");
      out.write("\t\t   \t\t}\r\n");
      out.write("\t\t\t}\t \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//alert(f.checkIds.value);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//단어 삭제\r\n");
      out.write("\tfunction deleteWord()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar f = document.managerForm;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcheckId();\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(f.checkIds.value==''){alert('선택된 리스트가 없습니다.'); return;}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tf.mode.value = 'delete';\r\n");
      out.write("\t\tf.target='processFrm';\r\n");
      out.write("\t\tf.action = \"popUpContents_ex_site_InsertUpdate.jsp\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//일괄저장\r\n");
      out.write("\tfunction saveChkKeywords(){\r\n");
      out.write("\t\talert('saveChkKeywords()');\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin-left: 15px\">\r\n");
      out.write("<form name=\"managerForm\" id=\"managerForm\" method=\"post\" onsubmit=\"return false;\">\r\n");
      out.write("<input type=\"hidden\" name=\"mode\" id=\"mode\">\r\n");
      out.write("<input type=\"hidden\" name=\"ekSeq\" id=\"ekSeq\">\r\n");
      out.write("<input type=\"hidden\" name=\"checkIds\" id =\"checkIds\">\r\n");
      out.write("<input type=\"hidden\" name=\"order\" id=\"order\">\r\n");
      out.write("<input type=\"hidden\" name=\"searchKey\" id=\"searchKey\">\r\n");
      out.write("<table style=\"width:100%;height:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"body_bg_top\" valign=\"top\">\r\n");
      out.write("\t\t<table style=\"width:820px;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t<!-- 타이틀 시작 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"tit_bg\" style=\"height: 67px; padding-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table style=\"width: 100%;\" border=\"0\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><img src=\"../../../images/admin/aekeyword/tit_icon.gif\" /><img src=\"../../../images/admin/ex_site/tit_05ex.gif\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"right\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"navi_home\">HOME</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"navi_arrow\">관리자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"navi_arrow2\">제외사이트 관리</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"15\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- 타이틀 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 검색 시작 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"search_box\">\r\n");
      out.write("\t\t\t\t<table id=\"search_box\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>검색 단어</th>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"vertical-align:middle\"><input style=\"width:500px;vertical-align:middle\" class=\"textbox\" type=\"text\" name=\"searchWord\" onkeypress=\"Javascript:if (event.keyCode == 13) { Search(); }\" style=\"vertical-align:middle\"><img src=\"../../../images/admin/aekeyword/btn_search.gif\" style=\"vertical-align:middle;cursor:pointer\" onclick=\"Search();\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 검색 끝 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"height:40px;\">\r\n");
      out.write("\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"../../../images/admin/aekeyword/btn_allselect.gif\" style=\"cursor:pointer\" onclick=\"selectAll(!document.managerForm.checkAll.checked);\"/></td>");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"../../../images/admin/aekeyword/btn_add2.gif\" style=\"cursor:pointer\" onclick=\"popupEdit('','insert');\"/></td>");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"../../../images/admin/aekeyword/btn_del.gif\" style=\"cursor:pointer\" onclick=\"deleteWord();\"/></td>");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 게시판 시작 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td id=\"behindExSiteList\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<!-- 게시판 끝 -->\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t<table align=\"center\" style=\"padding-top: 10px;\" border=\"0\"\r\n");
      out.write("\t\t\t\t\tcellpadding=\"0\" cellspacing=\"1\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<table id=\"paging\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<iframe name=\"processFrm\" height=\"0\" border=\"0\" style=\"display: none;\"></iframe>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
