/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:48:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.admin.ex_005fsite;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import risk.admin.ex_site.ExSiteMng;
import risk.util.ParseRequest;
import risk.util.ConfigUtil;

public final class admin_005fex_005fsite_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/admin/ex_site/../../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.admin.ex_site.ExSiteMng");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	System.out.println("■-------------admin_ex_site_edit.jsp----------------■");
	ParseRequest pr = new ParseRequest(request);
	pr.printParams();
	
	
	String s_seq = pr.getString("s_seq","");
	 String ekSeq= pr.getString("ekSeq","");	
	
	String searchWords = pr.getString("searchWords","");
	
	ExSiteMng eSMng = new ExSiteMng();
	
	
	String mode = pr.getString("mode"); 
	ArrayList arExSite = null;
	
	if(mode.equals("update")){
		arExSite = new ArrayList();
		arExSite = eSMng.updatePopUp_getExList(ekSeq, searchWords);
	}	


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../../css/base.css\" type=\"text/css\"/>\r\n");
      out.write("<script src=\"../../../js/ajax.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../../../js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction onLoadList(){\r\n");
      out.write("\t\tselectSgSite();\r\n");
      out.write("\t\tselectSSSite();\r\n");
      out.write("\t\tselectSiteURL();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction selectSgSite()\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\tdocument.getElementById('selectGroup').value = \"SG\";\r\n");
      out.write("\t\tajax.post(\"popUpContents_ex_site.jsp\", \"editForm\", \"td_SgSeq_SiteList\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction selectSSSite()\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\tdocument.getElementById('selectGroup').value = \"S\";\r\n");
      out.write("\t\tdocument.getElementById('sg_seq').value = '3'; //초기값: 18.트위터\r\n");
      out.write("\t\tajax.post(\"popUpContents_ex_site.jsp\", \"editForm\", \"td_SSeq_SiteList\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction selectSiteURL()\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\tdocument.getElementById('selectGroup').value = \"site_URL\";\r\n");
      out.write("\t\tajax.post(\"popUpContents_ex_site.jsp\", \"editForm\", \"td_siteUrl\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction selectSite(name, value)\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar targetId = \"\"; \r\n");
      out.write("\t\t//SG_SITE에서 선택시 S_SITE 타겟 td_SSeq_SiteList\r\n");
      out.write("\t\t//S_SITE에서 선택시 URL과 사이트 번호 보이기\r\n");
      out.write("\t\tif(name == 'SG_SITE') {\r\n");
      out.write("\t\t\t//target설정\r\n");
      out.write("\t\t\ttargetId = 'td_SSeq_SiteList';\r\n");
      out.write("\t\t\t//select S_SITE를 변경해 줘야함.\r\n");
      out.write("\t\t\tdocument.getElementById('selectGroup').value = \"S\";\r\n");
      out.write("\t\t\t//sg_seq넘기기\r\n");
      out.write("\t\t\tdocument.getElementById('sg_seq').value = value;\r\n");
      out.write("\t\t\tdocument.getElementById('s_seq').value = \"\"; //초기화\r\n");
      out.write("\t\t}else if(name == 'S_SITE'){\r\n");
      out.write("\t\t\t//siteUrl을 출력한다.\r\n");
      out.write("\t\t\ttargetId = 'td_siteUrl';\r\n");
      out.write("\t\t\t//사이트 URL과 번호를 출력해줘야함.\r\n");
      out.write("\t\t\tdocument.getElementById('selectGroup').value = \"site_URL\";\r\n");
      out.write("\t\t\t//sg_seq,s_seq넘기기 //sg_seq는 설정되어 있음.\r\n");
      out.write("\t\t\tdocument.getElementById('s_seq').value = value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//else targetId = ''; \r\n");
      out.write("\t\tdocument.getElementById(name).value = value;\r\n");
      out.write("\t\tajax.post('popUpContents_ex_site.jsp', 'editForm', targetId);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//URL 보이기\r\n");
      out.write("\t\tif(name == 'SG_SITE') {\r\n");
      out.write("\t\t\ttargetId = 'td_siteUrl';\r\n");
      out.write("\t\t\t//사이트 URL과 번호를 출력해줘야함.\r\n");
      out.write("\t\t\tdocument.getElementById('selectGroup').value = \"site_URL\";\r\n");
      out.write("\t\t\tajax.post('popUpContents_ex_site.jsp', 'editForm', targetId);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction excuteUpdateExSite(mode){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar f = document.editForm;\r\n");
      out.write("\t\t\tvar s_seq ");
 if (s_seq.equals("")) out.print(";"); else out.print("="+s_seq); 
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"ex_url\").value = document.getElementById(\"text_include\").value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"siteURL\").value = $(\"#siteUrl\").text();\r\n");
      out.write("\t\t\tif(mode == \"update\"){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"s_seq\").value = s_seq;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tf.action = \"popUpContents_ex_site_InsertUpdate.jsp\";\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body ");
 if(mode.equals("insert")) out.print("onload=" +"'onLoadList();'"); 
      out.write(" >\r\n");
      out.write("<form id=\"editForm\" name=\"editForm\" method=\"post\" action=\"\"> <!-- onsubmit=\"return false;\"  -->\r\n");
      out.write("<input type=\"hidden\" id= \"mode\" name=\"mode\" value=\"");
      out.print(mode);
      out.write("\"/>\r\n");
      out.write("<input type=\"hidden\" id= \"selectGroup\" name=\"selectGroup\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" id= \"sg_seq\" name=\"sg_seq\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" id= \"s_seq\" name=\"s_seq\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" id= \"ex_url\" name=\"ex_url\" value=\"\"/>\r\n");
      out.write("<input type=\"hidden\" id= \"siteURL\" name=\"siteURL\" value=\"\"/>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"ekSeq\" value=\"");
      out.print(ekSeq);
      out.write("\"/> \r\n");
      out.write("\r\n");

	if(mode.equals("insert")){
		

      out.write("\r\n");
      out.write("<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"10\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\" id=\"pop_head\" style=\"line-height:normal;\">\r\n");
      out.write("\t\t\t<p>제외사이트등록</p>\r\n");
      out.write("\t\t\t<span><a href=\"javascript:close();\"><img src=\"../../../images/search/pop_tit_close.gif\"></a></span>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table style=\"width:100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td style=\"padding-left:10px;padding-right:10px\" ><table id=\"board_01\"  style=\"width:100%;\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("    <!-- \t<tr>\r\n");
      out.write("\t\t\t<td width=\"23%\" style=\"padding: 3px 0px 0px 0px;\"><strong>구분</strong></td>\r\n");
      out.write("\t\t\t<td  style=\"padding: 3px 0px 0px 0px;\"><strong>내용</strong></td>\r\n");
      out.write("\t\t</tr> -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"23%\" style=\"padding: 3px 0px 0px 0px;\"><strong>그룹</strong></td>\r\n");
      out.write("\t\t\t<td width=\"100\" id=\"td_SgSeq_SiteList\" style=\"text-align: left\"></td> <!-- 그룹선택 -->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"23%\" style=\"padding: 3px 0px 0px 0px;\"><strong>사이트</strong></td>\t\r\n");
      out.write("\t\t\t<td  id=\"td_SSeq_SiteList\"  style=\"text-align: left\"></td> <!-- 사이트 -->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- URL 출력,사이트번호, 포함단어 출력-->\r\n");
      out.write("\t\t<tr >\r\n");
      out.write("\t\t\t<td width=\"100%\" colspan=\"3\" id=\"td_siteUrl\" style=\"text-align: left\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"378\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"40\" align=\"center\">\r\n");
      out.write("\t\t<img src=\"../../../images/admin/member_group/btn_save.gif\"  hspace=\"5\" onclick=\"excuteUpdateExSite('insert');\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t<img src=\"../../../images/admin/member/btn_cancel.gif\" onclick=\"window.close();\" style=\"cursor:pointer;\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	}else if(mode.equals("update")){ 
		
		String tmp[] = (String[]) arExSite.get(arExSite.size()-1);
		
		/* 
		tmp[0] = rs.getString("S_SEQ");
    	tmp[1] = rs.getString("EX_SEQ");
    	tmp[2] = rs.getString("EX_URL");
    	tmp[3] = rs.getString("EX_KEYWORD");
    	tmp[4] = rs.getString("S_NAME");
    	tmp[5] = rs.getString("SG_NAME"); */
		

      out.write("\r\n");
      out.write("<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"10\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\" id=\"pop_head\" style=\"line-height:normal;\">\r\n");
      out.write("\t\t\t<p>제외사이트수정</p>\r\n");
      out.write("\t\t\t<span><a href=\"javascript:close();\"><img src=\"../../../images/search/pop_tit_close.gif\"></a></span>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table style=\"width:100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td style=\"padding-left:10px;padding-right:10px\"><table id=\"board_01\" style=\"width:100%;\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<!-- <tr>\r\n");
      out.write("\t\t\t<td width=\"23%\" style=\"padding: 3px 0px 0px 0px;\"><strong>구분</strong></td>\r\n");
      out.write("\t\t\t<td  style=\"padding: 3px 0px 0px 0px;\"><strong>내용</strong></td>\r\n");
      out.write("\t\t</tr> -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"23%\" style=\"padding: 3px 0px 0px 0px;\"><strong>출처</strong></td>\r\n");
      out.write("\t\t\t<td width=\"100\" id=\"td_SgSeq_SiteList\" style=\"text-align: left\">");
out.print(tmp[4]);
      out.write("</td> <!-- 그룹선택 -->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"23%\" style=\"padding: 3px 0px 0px 0px;\"><strong>사이트</strong></td>\t\r\n");
      out.write("\t\t\t<td  id=\"td_SSeq_SiteList\"  style=\"text-align: left\">");
      out.print(tmp[3]);
      out.write("</td> <!-- 사이트 -->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- URL 출력 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"23%\" style=\"padding: 3px 0px 0px 3px;\" valign=\"top\"><strong>제외URL</strong></td>\r\n");
      out.write("\t\t\t<td colspan=\"4\"><textarea style=\"width: 100%;height: 100px;\" id=\"text_include\" style=\"text-align: left\">");
      out.print(tmp[2] );
      out.write("</textarea></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"378\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"40\" align=\"center\">\r\n");
      out.write("\t\t<img src=\"../../../images/admin/member_group/btn_modify.gif\"  hspace=\"5\" onclick=\"excuteUpdateExSite('update');\" style=\"cursor:pointer;\" >\r\n");
      out.write("\t\t<img src=\"../../../images/admin/member/btn_cancel.gif\" onclick=\"window.close();\" style=\"cursor:pointer;\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");

	}

      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
