/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:39:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.dashboard.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

 	Cookie[] cookies = request.getCookies(); //쿠키를 가져옴
	String Saveid = "";  				 // 쿠키에서 가져온 id저장
	String script = "";  				 // javascript 저장
	if(cookies != null){ 

		for(int i = 0;i<cookies.length;i++){
			System.out.println("cookies[i].getName():"+cookies[i].getName());
			if(cookies[i].getName().equals("lifeRSNid")){
				Saveid = cookies[i].getValue();				
			}			
		}			
	}else{
		
		System.out.println("not cookies!!");
		
	}

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/inc_page_top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/sha256.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdocument.title = \"Dashboard - Login\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction id_check() {\r\n");
      out.write("\t\t\tif( \"\" == $(\"#input_id\").val() ){\r\n");
      out.write("\t\t\t\talert('ID를  입력하십시오.');\r\n");
      out.write("\t\t\t\t$(\"#input_id\").focus();\r\n");
      out.write("\t\t\t}else if( \"\" == $(\"#input_pw\").val() ){\r\n");
      out.write("\t\t\t\talert('비밀번호를 입력하십시오.');\r\n");
      out.write("\t\t\t\t$(\"#input_pw\").focus();\r\n");
      out.write("\t\t\t}else{\t\r\n");
      out.write("\t\t\t\tvar security_pw = \"\";\r\n");
      out.write("\t\t\t\tif($(\"#input_pw\").val() == \"rsn1234!\") {\r\n");
      out.write("\t\t\t\t\tsecurity_pw = $(\"#input_pw\").val();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tsecurity_pw = SHA256($(\"#input_pw\").val());\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//alert(security_pw);\r\n");
      out.write("\t\t\t\t//alert(SHA256($(\"#input_pw\").val()));\r\n");
      out.write("\t\t\t\t$('#asLogin').append('<input type=\"hidden\" name=\"FimUserID\" value=\"'+$(\"#input_id\").val()+'\" /> ');\r\n");
      out.write("\t\t\t\t$('#asLogin').append('<input type=\"hidden\" name=\"FimUserPasswd\" value=\"'+security_pw+'\" /> ');\r\n");
      out.write("\t\t\t\tif($(\"#remember_id\").is(\":checked\")){\r\n");
      out.write("\t\t\t\t\t$('#asLogin').append('<input type=\"hidden\" name=\"SaveId\" value=\"'+$(\"#input_id\").val()+'\" /> ');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('#asLogin').submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrap\" class=\"login\">\r\n");
      out.write("\t\t<div class=\"wrap\">\r\n");
      out.write("            <form id=\"asLogin\" name=\"asLogin\" action=\"/login.jsp\" method=\"POST\">\r\n");
      out.write("                <div class=\"wrap\">\r\n");
      out.write("                    <h1>Hello :D</h1>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\"><input type=\"text\" id=\"input_id\"  placeholder=\"ID\" required><label for=\"input_id\"></label></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\"><input type=\"password\" id=\"input_pw\" OnKeyDown=\"Javascript:if (event.keyCode == 13) { id_check();}\" placeholder=\"PASSWORD\" required><label for=\"input_pw\"></label></div>\r\n");
      out.write("                    <button class=\"ui_btn ui_wid_100p btn_login\" onclick=\"id_check()\"><span class=\"txt\">Log In</span></button>\r\n");
      out.write("                    <div class=\"txt\">* 서비스 문의는 <a href=\"mailto:solution@realsn.com\">solution@realsn.com</a>으로 보내주시기 바랍니다.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdesignScripts();\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
