/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-27 07:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.admin.aekeyword;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import risk.admin.aekeyword.ExceptionKeywordBean;
import risk.admin.aekeyword.ExceptionKeywordMgr;
import risk.util.ParseRequest;
import java.net.*;
import risk.util.ConfigUtil;

public final class behind_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/admin/aekeyword/../../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("risk.admin.aekeyword.ExceptionKeywordMgr");
    _jspx_imports_classes.add("risk.admin.aekeyword.ExceptionKeywordBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	
	ParseRequest    pr = new ParseRequest(request);
	pr.printParams();
	
	//AJAX  사용시 한글 처리
	//URLDecoder ud = new URLDecoder();
	String searchWord = pr.getString("searchWord");			//검색어
	String order = pr.getString("order", "EK_VALUE ASC");	//정렬 순서
	
	String str_word = "";
	String str_weight = "";
	String str_writer = "";
	String str_date = "";
	
	String ico_word = "";
	String ico_weight = "";
	String ico_writer = "";
	String ico_date = "";
	
	if( order.equals("EK_VALUE ASC") ) {
		str_word = "EK_VALUE DESC";		
		str_writer = "EK_FWRITTER ASC";
		str_date = "EK_DATE DESC";
		ico_word = "▲";
	}else if( order.equals("EK_VALUE DESC") ) {
		str_word = "EK_VALUE ASC";		
		str_writer = "EK_FWRITTER ASC";
		str_date = "EK_DATE DESC";
		ico_word = "▼";
	}else if( order.equals("EK_FWRITTER ASC") ) {
		str_word = "EK_VALUE ASC";		
		str_writer = "EK_FWRITTER DESC";
		str_date = "EK_DATE DESC";
		ico_writer = "▲";
	}else if( order.equals("EK_FWRITTER DESC") ) {
		str_word = "EK_VALUE ASC";		
		str_writer = "EK_FWRITTER ASC";
		str_date = "EK_DATE DESC";
		ico_writer = "▼";
	}else if( order.equals("EK_DATE DESC") ) {
		str_word = "EK_VALUE ASC";		
		str_writer = "EK_FWRITTER ASC";
		str_date = "EK_DATE ASC";
		ico_date = "▼";
	}else if( order.equals("EK_DATE ASC") ) {
		str_word = "EK_VALUE ASC";
		str_weight = "EK_FWRITTER DESC";		
		str_date = "EK_DATE DESC";
		ico_date = "▲";
	}
	
	ExceptionKeywordMgr ekMgr = new ExceptionKeywordMgr();
	ExceptionKeywordBean[] arrEKbean = null;
	arrEKbean = ekMgr.getKeywordList(searchWord, order);	

      out.write("\r\n");
      out.write("<table id=\"board_01\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("<col width=\"5%\"><col width=\"35%\"><col width=\"12%\"><col width=\"12%\"><col width=\"12%\"><col width=\"12%\"><col width=\"12%\">\r\n");
      out.write("\t<tr>               \r\n");
      out.write("\t\t<th><input type=\"checkbox\" name=\"checkAll\" onclick=\"selectAll(this.checked);\"></th>\r\n");
      out.write("\t\t<th onclick=\"excuteOrder('");
      out.print(str_word);
      out.write("');\" style=\"cursor:pointer\">키워드</th>\r\n");
      out.write("\t\t<th>검색조건</th>\r\n");
      out.write("\t\t<th onclick=\"excuteOrder('");
      out.print(str_writer);
      out.write("');\" style=\"cursor:pointer\">등록자</th>\r\n");
      out.write("\t\t<th onclick=\"excuteOrder('");
      out.print(str_date);
      out.write("');\" style=\"cursor:pointer\">등록일</th>\r\n");
      out.write("\t\t<th>수정자</th>\r\n");
      out.write("\t\t<th>수정일</th>\r\n");
      out.write("\t</tr>\r\n");

	if(arrEKbean != null && arrEKbean.length > 0){
		for(int i = 0; i < arrEKbean.length; i++){

      out.write(" \r\n");
      out.write("\t<tr>         \r\n");
      out.write("\t\t<td><input type=\"checkbox\" name=\"checkId\" value=\"");
      out.print(arrEKbean[i].getEkSeq());
      out.write("\"></td>\r\n");
      out.write("\t\t<td><p class=\"board_01_tit\" onclick=\"popupEdit('");
      out.print(arrEKbean[i].getEkSeq());
      out.write("','update');\" style=\"cursor:pointer\">");
      out.print(arrEKbean[i].getEkValue());
      out.write("</p></td>\r\n");
      out.write("\t\t<td>");
      out.print(arrEKbean[i].getK_op_type());
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(arrEKbean[i].getEkFwriter());
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(arrEKbean[i].getEkDate());
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(arrEKbean[i].getEkLwriter());
      out.write("</td>\r\n");
      out.write("\t\t<td>");
      out.print(arrEKbean[i].getEkUpdate());
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");

		}
	}else{

      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"6\" style=\"height:40px;font-weight:bold\" align=\"center\">조건에 맞는 데이터가 없습니다.</td>\r\n");
      out.write("\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("</table>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
