/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-28 01:50:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.issue;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import risk.util.ParseRequest;
import risk.util.DateUtil;
import risk.util.StringUtil;
import risk.util.PageIndex;
import risk.search.userEnvInfo;
import risk.issue.IssueMgr;
import risk.issue.IssueDataBean;
import java.util.ArrayList;
import risk.util.ConfigUtil;
import java.net.URLDecoder;
import java.util.HashMap;

public final class issue_005fdata_005fexcel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/issue/../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.search.userEnvInfo");
    _jspx_imports_classes.add("risk.util.PageIndex");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("risk.issue.IssueDataBean");
    _jspx_imports_classes.add("risk.issue.IssueMgr");
    _jspx_imports_classes.add("risk.util.DateUtil");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("risk.util.StringUtil");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("application/vnd.ms-excel;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

//@ page contentType="text/html; charset=EUC-KR" 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//try{
	ParseRequest pr = new ParseRequest(request);
	pr.printParams();

	String id_seqs = pr.getString("id_seqs", "");
	String sDateFrom = pr.getString("param_sDate");
	String sDateTo = pr.getString("param_eDate");
	String ir_stime = pr.getString("param_sTime", "16");
	String ir_etime = pr.getString("param_eTime", "15");
	
	String typeCodeSeries = pr.getString("typeCodeSelect");
	String sentiSeries = pr.getString("typeCodeSenti");
	String transSeries = pr.getString("typeTransyn");
	String infoSeries = pr.getString("typeCodeInfo");
	String relationKeywordSeries = pr.getString("relationKeyword");
	String register = pr.getString("register");
	String searchKeyword = URLDecoder.decode(pr.getString("param_searchKey"), "UTF-8");
	String searchKeyType = pr.getString("param_keyType");
	String sltSiteGroups = pr.getString("sltSiteGroups","");
	
	//세션정보 가져오기~~
  	userEnvInfo uei = null;
    uei = (userEnvInfo) session.getAttribute("ENV");
	
    // 데이터 정렬
    String sOrder       = pr.getString("sOrder","MD_DATE");
    String sOrderAlign  = pr.getString("sOrderAlign","DESC"); 
	uei.setOrder( sOrder );
    uei.setOrderAlign( sOrderAlign );
	
  	//검색날짜 설정 : 기본 7일간 검색한다.
  	DateUtil du = new DateUtil();
  	String sCurrDate    = du.getCurrentDate();
  	if (sDateTo.equals("")) sDateTo = du.getCurrentDate();
  	if (sDateFrom.equals("")) {
  		du.addDay(-1);
  		sDateFrom = du.getDate();
  	}	
    
    String setStime = "";
	String setEtime = "";
	if(ir_stime.equals("24")){
		setStime = "23:59:59";	
	}else{
		setStime = ir_stime + ":00:00";
	}
	if(ir_etime.equals("24")){
		setEtime = "23:59:59";	
	}else{
		setEtime = ir_etime + ":59:59";
	}
		
    IssueMgr issueMgr = new IssueMgr();
	ArrayList arrIdBean = issueMgr.getIssueDataExcel(id_seqs, sDateFrom, setStime, sDateTo, setEtime, typeCodeSeries, sentiSeries, infoSeries, relationKeywordSeries
			, searchKeyType, searchKeyword, register, uei.getOrder(), uei.getOrderAlign(), sltSiteGroups, transSeries);
	
	HashMap<String, String> codeMap = new HashMap<String, String>();
	codeMap = issueMgr.getCodeSiteGroupMap();
	
  
	response.setContentType("application/vnd.ms-excel; charset=EUC-KR") ;
    response.setHeader("Content-Disposition", "attachment;filename=Issue_Data_"+ du.getCurrentDate("yyyyMMdd") +".xls");
    response.setHeader("Content-Description", "JSP Generated Data");
   

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write("td { font-size:12px; color:#333333; font-family:\"gulim\"; ; line-height: 18px}\r\n");
      out.write("   input { font-size:12px; border:0px solid #CFCFCF; height:16px; color:#767676; }\r\n");
      out.write(".t {  font-family: \"Tahoma\"; font-size: 11px; color: #666666}\r\n");
      out.write("   .tCopy { font-family: \"Tahoma\"; font-size: 12px; color: #000000; font-weight: bold}\r\n");
      out.write("a:link { color: #333333; text-decoration: none; }\r\n");
      out.write("a:visited { text-decoration: none; color: #000000; }\r\n");
      out.write("a:hover { text-decoration: none; color: #FF9900; }\r\n");
      out.write("a:active { text-decoration: none; }\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\tSCROLLBAR-face-color: #F2F2F2;\r\n");
      out.write("\tSCROLLBAR-shadow-color: #999999;\r\n");
      out.write("\tSCROLLBAR-highlight-color: #999999;\r\n");
      out.write("\tSCROLLBAR-3dlight-color: #FFFFFF;\r\n");
      out.write("\tSCROLLBAR-darkshadow-color: #FFFFFF;\r\n");
      out.write("\tSCROLLBAR-track-color: #F2F2F2;\r\n");
      out.write("\tSCROLLBAR-arrow-color: #333333;\r\n");
      out.write("     }\r\n");
      out.write(".menu_black {  font-family: \"돋움\", \"돋움체\"; font-size: 12px; line-height: 16px; color: #000000}\r\n");
      out.write(".textw { font-family: \"돋움\", \"돋움체\"; font-size: 12px; line-height: normal; color: #FFFFFF; font-weight: normal}\r\n");
      out.write("\r\n");
      out.write(".menu_blue {\r\n");
      out.write("\tfont-family: \"돋움\", \"돋움체\";\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 16px;\r\n");
      out.write("\tcolor: #3D679C;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".menu_gray {\r\n");
      out.write("font-family: \"돋움\", \"돋움체\"; font-size: 12px; line-height: 16px; color: #4B4B4B\r\n");
      out.write("}\r\n");
      out.write(".menu_red {\r\n");
      out.write("font-family: \"돋움\", \"돋움체\"; font-size: 12px; line-height: 16px; color: #CC0000\r\n");
      out.write("}\r\n");
      out.write(".menu_blueOver {\r\n");
      out.write("\r\n");
      out.write("\tfont-family: Tahoma;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tline-height: 16px;\r\n");
      out.write("\tcolor: #3D679C;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".menu_blueTEXTover {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfont-family: \"돋움\", \"돋움체\";\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 16px;\r\n");
      out.write("\tcolor: #3366CC;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".textwbig {\r\n");
      out.write("font-family: \"돋움\", \"돋움체\"; font-size: 14px; line-height: normal; color: #FFFFFF; font-weight: normal\r\n");
      out.write("}\r\n");
      out.write(".textBbig {\r\n");
      out.write("\r\n");
      out.write("font-family: \"돋움\", \"돋움체\"; font-size: 14px; line-height: normal; color: #000000; font-weight: normal\r\n");
      out.write("}\r\n");
      out.write(".menu_grayline {\r\n");
      out.write("\tfont-family: \"돋움\", \"돋움체\";\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 16px;\r\n");
      out.write("\tcolor: #4B4B4B;\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write(".menu_grayS {\r\n");
      out.write("\r\n");
      out.write("font-family: \"돋움\", \"돋움체\"; font-size: 11px; line-height: 16px; color: #4B4B4B\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\" border=\"1\" >\r\n");
      out.write("    <table width=\"2400\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("     \r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"120\" align=\"center\" bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 출처     </strong></td>\r\n");
      out.write("        <td width=\"440\" align=\"center\" bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 제목     </strong></td>\r\n");
      out.write("        <td width=\"200\" align=\"center\" bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> URL     </strong></td>\r\n");
      out.write("        <td width=\"200\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 수집 시간 </strong></td>   \r\n");
      out.write("        <td width=\"200\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 구분 </strong></td>   \r\n");
      out.write("        <td width=\"200\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 신라호텔 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 신라모노그램 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 신라스테이 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 호텔_리스크·VOC 유형 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 영업점 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> TR_리스크·VOC 유형 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 자회사·계열사 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> SHP_리스크·VOC 유형 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> SBTM_리스크·VOC 유형 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> CEO/경영진_리스크·VOC 유형 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 사업/IR/준법/임직원 등_리스크·VOC 유형 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 정부/ESG 등_리스크·VOC 유형 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 리스크·VOC 등급 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 영향력 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 성향 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 사이트그룹 </strong></td>   \r\n");
      out.write("        <td width=\"100\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 연관어 </strong></td>   \r\n");
      out.write("        <td width=\"120\" align=\"center\"  bgcolor=\"#C0C0C0\"  style=\"padding: 3px 0px 0px 0px;\"> <strong> 등록자  </strong></td>        \r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t  \r\n");
      out.write("    </table>\r\n");
      out.write("    ");
  
    
    	String strClout = "";
    	String strSenti = "";
    	for( int i = 0 ; i < arrIdBean.size() ; i++ ) {
    	
	    	IssueDataBean IDBean = new IssueDataBean();
	    	IDBean = (IssueDataBean) arrIdBean.get(i);
	    	
	      	String[] ar_SiteCnt = IDBean.getMd_same_ct().split(",");
	      	
	      	String code1 = "-";
	      	if(!IDBean.getCode1().equals("")) {
	      		code1 = IDBean.getCode1();
 	      	}
	      	
	      	String code2 = "-";
	      	if(!IDBean.getCode2().equals("")) {
	      		code2 = IDBean.getCode2();
 	      	}
	      	
	      	String code3 = "-";
	      	if(!IDBean.getCode3().equals("")) {
	      		code3 = IDBean.getCode3();
 	      	}
	      	
	      	String code4 = "-";
	      	if(!IDBean.getCode4().equals("")) {
	      		code4 = IDBean.getCode4();
 	      	}
	      	
	      	String code5 = "-";
	      	if(!IDBean.getCode5().equals("")) {
	      		code5 = IDBean.getCode5();
 	      	}
	      	
	      	String code6 = "-";
	      	if(!IDBean.getCode6().equals("")) {
	      		code6 = IDBean.getCode6();
 	      	}
	      	
	      	String code7 = "-";
	      	if(!IDBean.getCode7().equals("")) {
	      		code7 = IDBean.getCode7();
 	      	}
	      	
	      	String code8 = "-";
	      	if(!IDBean.getCode8().equals("")) {
	      		code8 = IDBean.getCode8();
 	      	}
	      	
	      	String code9 = "-";
	      	if(!IDBean.getCode9().equals("")) {
	      		code9 = IDBean.getCode9();
 	      	}
	      	
	      	String code10 = "-";
	      	if(!IDBean.getCode10().equals("")) {
	      		code10 = IDBean.getCode10();
 	      	}
	      	
	      	String code11 = "-";
	      	if(!IDBean.getCode11().equals("")) {
	      		code11 = IDBean.getCode11();
 	      	}
	      	
	      	String code12 = "-";
	      	if(!IDBean.getCode12().equals("")) {
	      		code12 = IDBean.getCode12();
 	      	}
	      	
	      	String code13 = "-";
	      	if(!IDBean.getCode13().equals("")) {
	      		code13 = IDBean.getCode13();
 	      	}
	      	
	      	String code14 = "-";
	      	if(!IDBean.getCode14().equals("")) {
	      		code14 = IDBean.getCode14();
 	      	}
	      	
 	      	if(IDBean.getId_clout().equals("1")){
 	      		strClout = "파워";
	      	}else if(IDBean.getId_clout().equals("2")){
	      		strClout = "일반";
	      	}

	      	if(IDBean.getSenti().equals("1")){
	      		strSenti = "긍정";
	      	}else if(IDBean.getSenti().equals("2")){
	      		strSenti = "부정";
	      	}else {
	      		strSenti = "중립";
	      	}
			
 	      	String reportyn = "미포함";
 	      	if(IDBean.getId_reportyn().equals("Y")) {
 	      		reportyn = "포함";
 	      	}
 	      	
    
      out.write("\r\n");
      out.write("    <table width=\"4480\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"120\" align=\"center\" class=\"menu_gray\" style=\"padding: 3px 0px 0px 0px;\">\r\n");
      out.write("          ");
      out.print(IDBean.getMd_site_name());
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        \r\n");
      out.write("        <td width=\"440\" align=\"center\" class=\"menu_gray\" style=\"padding: 3px 0px 0px 0px;\">\r\n");
      out.write("          ");
      out.print(IDBean.getId_title());
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        \r\n");
      out.write("        <td width=\"200\" align=\"center\" class=\"menu_gray\" style=\"padding: 3px 0px 0px 0px; text-overflow : ellipsis; overflow : hidden;\">\r\n");
      out.write("          <nobr>");
      out.print(IDBean.getId_url());
      out.write("</nobr>\r\n");
      out.write("        </td>\r\n");
      out.write("\t\t\r\n");
      out.write("        <td width=\"200\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(IDBean.getMd_date());
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code1);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code3);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code4);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code5);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code6);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code7);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code8);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code9);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code10);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code11);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code12);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code13);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code14);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(code2);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("        <td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(strClout);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("        <td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(strSenti);
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("        \r\n");
      out.write("        <td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(codeMap.get(IDBean.getSg_seq()));
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("                \r\n");
      out.write("         <td width=\"100\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(IDBean.getRelationkeys());
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("         <td width=\"120\" align=\"center\" style=\"padding: 3px 0px 0px 5px;\">\r\n");
      out.write("          ");
      out.print(IDBean.getM_name());
      out.write("\r\n");
      out.write("        </td>\r\n");
      out.write("            \r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    ");
  }
      out.write("\r\n");
      out.write("          ");
//}catch(Exception e){System.out.println("issue_data_excel.jsp : "+e);} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
