/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2022-07-28 01:23:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.riskv3.issue;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Map;
import risk.util.ParseRequest;
import risk.util.DateUtil;
import risk.util.StringUtil;
import risk.util.RsnAnalysis;
import risk.search.MetaBean;
import risk.search.MetaMgr;
import risk.search.DomainKeywordMgr;
import risk.issue.IssueCodeMgr;
import risk.issue.IssueDataBean;
import risk.issue.IssueCommentBean;
import risk.issue.IssueMgr;
import risk.issue.IssueCodeBean;
import risk.util.ConfigUtil;

public final class pop_005fissue_005fdata_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/riskv3/issue/../inc/sessioncheck.jsp", Long.valueOf(1658907412822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("risk.search.DomainKeywordMgr");
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("risk.issue.IssueCodeMgr");
    _jspx_imports_classes.add("risk.util.RsnAnalysis");
    _jspx_imports_classes.add("risk.issue.IssueDataBean");
    _jspx_imports_classes.add("risk.issue.IssueMgr");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("risk.util.StringUtil");
    _jspx_imports_classes.add("risk.issue.IssueCommentBean");
    _jspx_imports_classes.add("risk.search.MetaBean");
    _jspx_imports_classes.add("risk.util.ConfigUtil");
    _jspx_imports_classes.add("risk.util.ParseRequest");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("risk.util.DateUtil");
    _jspx_imports_classes.add("risk.issue.IssueCodeBean");
    _jspx_imports_classes.add("risk.search.MetaMgr");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
//@ page contentType="text/html; charset=euc-kr"
      out.write("\r\n");
      out.write("\r\n");

    
	String SS_M_NO = (String)session.getAttribute("SS_M_NO")   == null ? "": (String)session.getAttribute("SS_M_NO")  ;
    String SS_M_ID = (String)session.getAttribute("SS_M_ID")   == null ? "": (String)session.getAttribute("SS_M_ID")  ;
    String SS_M_NAME = (String)session.getAttribute("SS_M_NAME") == null ? "": (String)session.getAttribute("SS_M_NAME");
    String SS_MG_NO = (String)session.getAttribute("SS_MG_NO")  == null ? "": (String)session.getAttribute("SS_MG_NO") ;
	String SS_TITLE = (String)session.getAttribute("SS_TITLE")  == null ? "": (String)session.getAttribute("SS_TITLE");
    String SS_URL =   (String)session.getAttribute("SS_URL")    == null ? "": (String)session.getAttribute("SS_URL") ;
    String SS_M_DEPT =   (String)session.getAttribute("SS_M_DEPT")    == null ? "": (String)session.getAttribute("SS_M_DEPT") ;    
    String SS_M_IP =   (String)session.getAttribute("SS_M_IP")    == null ? "": (String)session.getAttribute("SS_M_IP") ;    
    String SS_M_MAIL =   (String)session.getAttribute("SS_M_MAIL")    == null ? "": (String)session.getAttribute("SS_M_MAIL") ;    
	String SS_M_ORGVIEW_USEYN = (String)session.getAttribute("SS_M_ORGVIEW_USEYN")    == null ? "": (String)session.getAttribute("SS_M_ORGVIEW_USEYN") ;    
	String SS_ML_URL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
	
	String SS_SEARCHDATE = (String)session.getAttribute("SS_SEARCHDATE")    == null ? "": (String)session.getAttribute("SS_SEARCHDATE") ;
	
	
    

	if ((SS_M_ID.equals("")) || !SS_M_IP.equals(request.getRemoteAddr()) ) {
		ConfigUtil cu = new ConfigUtil();
		out.print("<SCRIPT Language=JavaScript>");
		//out.print("window.setTimeout( \" top.document.location = "+cu.getConfig("URL")+"'riskv3/error/sessionerror.jsp' \") ");
		out.print("top.document.location = '"+cu.getConfig("URL")+"risk/sessionerror.jsp'");
        out.print("</SCRIPT>");
    }
	

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	ParseRequest pr = new ParseRequest(request);
	pr.printParams();
	
	DateUtil	 du = new DateUtil();
	StringUtil	 su = new StringUtil();
	MetaMgr  metaMgr = new MetaMgr();
	DomainKeywordMgr  dkMgr = new DomainKeywordMgr();
	IssueCodeMgr icm = new IssueCodeMgr();
	IssueMgr issueMgr = new IssueMgr();
	RsnAnalysis ana = new RsnAnalysis();
	
	// Parameter
	String txtcmt = pr.getString("txtcmt");
	
	
	//카드,캐피탈,커머셜 코멘트
/*  String hycard_txtcmt = pr.getString("hycard_txtcmt");
	String hycap_txtcmt = pr.getString("hycap_txtcmt");
	String hycom_txtcmt = pr.getString("hycom_txtcmt");
 */	
 
	String txtcmt2 = pr.getString("txtcmt2");
	String mode = pr.getString("mode");
	String mode2 = pr.getString("mode2","");
	String subMode = pr.getString("subMode","");
	String md_seq = pr.getString("md_seq");
	String md_seqs = pr.getString("md_seqs");
	String id_seqs = pr.getString("id_seqs");
	String child = pr.getString("child", "");
	String menu = pr.getString("menu","");
	String rp_count = pr.getString("rp_count");
	String rp_count2 = pr.getString("rp_count2");
	
	
	// Bean
	IssueDataBean idBean = new IssueDataBean();
	MetaBean metaBean = new MetaBean();
	IssueCommentBean icmBean = null;
	int ic_seq = 0;
	String hytype = "";
	String hycode = "";
	ArrayList arrIcBean = null;
	ArrayList subArrIcBean = null;
	//분류체계코드 (0:분류항목 포함, 1:분류항목 제외)
	icm.init(0);		
	Map issueCodeMap = null;
	Map issueCodeDetailMap = null;
	Map relationKeywordR_Map = null;
	String relationkeywordR_str = "";
	
	//Depth가 1Depth이상인 기준 IC_TYPE (고객사마다 다름) 
	//String parentTypes = "1,11,12,13,14,18,17,16,15,19,21,22,23,24,28,27,26,25,29,31,32,33,34,38,37,36,35,39"; 
	String parentTypes = "1,3,4,5,6,7,8,9,10,11,12,13,14,2"; 
	//String requisiteParentTypes = "12,13,14,22,23,24,32,33,34"; //필수체크항목 (주제, 게시물 유형, 성향)
	
	//String hycard_requisiteParentTypes ="12,13,14"; // 현카드 필수체크항목 (주제, 게시물 유형, 성향)
	//String hycap_requisiteParentTypes = "22,23,24"; // 현캐피 필수체크항목 (주제, 게시물 유형, 성향)
	//String hycom_requisiteParentTypes = "32,33,34"; // 현커머 필수체크항목 (주제, 게시물 유형, 성향)
	
	HashMap<String, ArrayList<String[]>> subDepthList = issueMgr.getSubdepthList(parentTypes); //parentTypes 하위 뎁스 리스트
	ArrayList<String[]> autoLastDepthCodeList;
	HashMap<String, String> autoCheckMap = new HashMap<String, String>();

	//자동롤링용 연관키워드 한줄로 만들기
	ArrayList relationKeyAll = issueMgr.getRelationKey();

	StringBuffer relKey_buff = null;
	String streamKey = "";
	if (relationKeyAll.size() > 0) {
		for (int i = 0; i < relationKeyAll.size(); i++) {

	if (relKey_buff == null) {
		relKey_buff = new StringBuffer((String) relationKeyAll.get(i));
	} else {
		relKey_buff.append(",").append((String) relationKeyAll.get(i));
	}
		}

		if (relKey_buff != null) {
	streamKey = relKey_buff.toString();
		}
	}

	String autoCompleteSite = "";

	if (mode.equals("insert")) {
		//메타 정보
		if (subMode.equals("solr")) {
			metaBean.setMd_seq(pr.getString("md_seq"));
			metaBean.setS_seq(pr.getString("s_seq"));
			metaBean.setSg_seq(pr.getString("sg_seq"));
			metaBean.setMd_site_name(pr.getString("md_site_name"));
			metaBean.setMd_site_menu("SOLR");
			metaBean.setMd_date(du.getDate(pr.getString("md_date"), "yyyy-MM-dd HH:mm:ss"));
			metaBean.setMd_title(su.dbString(pr.getString("md_title")));
			metaBean.setMd_url(su.dbString(pr.getString("md_url")));
			metaBean.setL_alpha("KOR");
		} else if (subMode.equals("TOP")) {
			metaBean = metaMgr.getTopData(md_seq);
			//ic_seq = icm.getSiteMapCode(metaBean.getSg_seq());  //사이트 이슈 코드 맵핑 정보 코드 시퀀스로 가져옴
		} else if (subMode.equals("warning")) {
			metaBean = metaMgr.getWarningMetaData(md_seq, mode2);
			//ic_seq = icm.getSiteMapCode(metaBean.getSg_seq());  //사이트 이슈 코드 맵핑 정보 코드 시퀀스로 가져옴
			autoLastDepthCodeList = metaMgr.getLastDepthMapList(metaBean.getMd_seq());
			autoCheckMap = metaMgr.getAutoMap(autoLastDepthCodeList);

		} else if(subMode.equals("domain")) {
			metaBean = dkMgr.getMetaData(md_seq, mode2);
			autoLastDepthCodeList = dkMgr.getLastDepthMapList(metaBean.getMd_seq()); 
			autoCheckMap = dkMgr.getAutoMap(autoLastDepthCodeList);	
		}else {
			metaBean = metaMgr.getMetaData(md_seq, mode2);
			//ic_seq = icm.getSiteMapCode(metaBean.getSg_seq());  //사이트 이슈 코드 맵핑 정보 코드 시퀀스로 가져옴
			autoLastDepthCodeList = metaMgr.getLastDepthMapList(metaBean.getMd_seq());
			autoCheckMap = metaMgr.getAutoMap(autoLastDepthCodeList);

		}
	} else if (mode.equals("update")) {
		
		//이슈 정보
		idBean = issueMgr.getIssueDataBean_V2(md_seq);
		issueCodeMap = issueMgr.getIssueDataCodeMap(idBean.getId_seq());
		//relationKeywordR_Map = issueMgr.getRelationKeywordR_Map(idBean.getId_seq());
		relationkeywordR_str  = issueMgr.getRelationKeyword_str(idBean.getId_seq());
		icmBean = issueMgr.SelectIssueComment(idBean.getId_seq());
	} else if (mode.equals("new")) {
		ArrayList arAutoCompleteSite = issueMgr.getAutoCompleteSite();
		StringBuffer strBuffer = null;
		for (int i = 0; i < arAutoCompleteSite.size(); i++) {
	if (strBuffer == null) {
		strBuffer = new StringBuffer((String) arAutoCompleteSite.get(i));
	} else {
		strBuffer.append(",").append((String) arAutoCompleteSite.get(i));
	}
		}
		if (relKey_buff != null) {
			autoCompleteSite = strBuffer.toString();
		}

	}
	//자동 맵핑

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<title></title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/base.css\" />\r\n");
      out.write("\t<link href=\"../../css/jquery.autocomplete.css\" rel=\"stylesheet\"type=\"text/css\" />\r\n");
      out.write("\t<script src=\"../../js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"../../js/ajax.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"../../js/popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"../issue/js/issue_popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"../../js/common.js\"  type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"../../js/jquery.autocomplete.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<iframe id=\"if_samelist\" name=\"if_samelist\" width=\"100%\" height=\"0\" src=\"about:blank\"></iframe>\r\n");
      out.write("\t<img  id=\"sending\" src=\"../../images/search/saving.gif\" style=\"position: absolute;  \" >\r\n");
      out.write("\t<input name=\"streamKey\" id=\"streamKey\" type=\"hidden\" value=\"");
      out.print(streamKey);
      out.write("\">\r\n");
      out.write("\t<input name=\"autoCompleteSite\" id=\"autoCompleteSite\" type=\"hidden\" value=\"");
      out.print(autoCompleteSite);
      out.write("\">\r\n");
      out.write("\t<form name=\"fSend\" id=\"fSend\" action=\"issue_data_prc.jsp\" method=\"post\" onsubmit=\"return false;\">\r\n");
      out.write("\t\t<input name=\"mode\" id=\"mode\" type=\"hidden\" value=\"");
      out.print(mode);
      out.write("\"><!-- 모드 -->\t\r\n");
      out.write("\t\t<input name=\"rp_count\" id=\"rp_count\" type=\"hidden\" value=\"");
      out.print(rp_count);
      out.write("\">\r\n");
      out.write("\t\t<input name=\"txtcmt\" id=\"txtcmt\" type=\"hidden\" value=\"");
      out.print(txtcmt);
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"mode2\" value=\"");
      out.print(mode2 );
      out.write("\">\r\n");
      out.write("\t\t<input name=\"menu\" id=\"menu\" type=\"hidden\" value=\"");
      out.print(menu);
      out.write("\">\r\n");
      out.write("\t\t<input name=\"typeCodes\" id=\"typeCodes\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t<input name=\"subMode\" id=\"subMode\" type=\"hidden\" value=\"");
      out.print(subMode );
      out.write("\">\r\n");
      out.write("\t<!-- \t<input name=\"typeCodesDetail\" id=\"typeCodesDetail\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t<input name=\"typeCodesInfo\" id=\"typeCodesInfo\" type=\"hidden\" value=\"\">-->\r\n");
      out.write("\t\t<input name=\"relationkeyCode\" id=\"relationkeyCode\" type=\"hidden\" value=\"\"> \r\n");
      out.write("\t\t<input name=\"relationkeyNames\" id=\"relationkeyNames\" type=\"hidden\" value=\"\"> \r\n");
      out.write("\t\t<input name=\"relationkeyNames1\" id=\"relationkeyNames1\" type=\"hidden\" value=\"\"> \r\n");
      out.write("\t\t<input name=\"relationkeyNames2\" id=\"relationkeyNames2\" type=\"hidden\" value=\"\"> \r\n");
      out.write("\t\t<input name=\"relationkeyAutoNames\" id=\"relationkeyAutoNames\" type=\"hidden\" value=\"\"> \r\n");
      out.write("\t\t<input name=\"param_ic_type\" id=\"param_ic_type\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t<input name=\"parentTypes\" id=\"parentTypes\" type=\"hidden\" value=\"");
      out.print(parentTypes);
      out.write("\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input name=\"cloutType\" id=\"cloutType\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t<input name=\"sentiType\" id=\"sentiType\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t<input name=\"transType\" id=\"transType\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t");
if(mode.equals("insert")){ 
      out.write("\r\n");
      out.write("\t\t\t<input name=\"md_seq\" id=\"md_seq\" type=\"hidden\" value=\"");
      out.print(metaBean.getMd_seq());
      out.write("\"><!-- 기사번호 -->\r\n");
      out.write("\t\t\t<input name=\"md_pseq\" id=\"md_pseq\" type=\"hidden\" value=\"");
      out.print(metaBean.getMd_pseq());
      out.write("\"><!-- 모 기사번호 -->\r\n");
      out.write("\t\t\t<input name=\"s_seq\" id=\"s_seq\" type=\"hidden\" value=\"");
      out.print(metaBean.getS_seq());
      out.write("\"><!-- 사이트번호 -->\r\n");
      out.write("\t\t\t<input name=\"sg_seq\" id=\"sg_seq\" type=\"hidden\" value=\"");
      out.print(metaBean.getSg_seq());
      out.write("\"><!-- 사이트 그룹 -->\r\n");
      out.write("\t\t\t<input name=\"md_date\" id=\"md_date\" type=\"hidden\" value=\"");
      out.print(metaBean.getMd_date());
      out.write("\"><!-- 수십 시간-->\r\n");
      out.write("\t\t\t<input name=\"md_site_menu\" id=\"md_site_menu\" type=\"hidden\" value=\"");
      out.print(metaBean.getMd_site_menu());
      out.write("\"><!-- 사이트 메뉴 -->\r\n");
      out.write("\t\t\t<input name=\"md_same_ct\" id=\"md_same_ct\" type=\"hidden\" value=\"");
      out.print(metaBean.getMd_same_count());
      out.write("\"><!-- 유사개수 -->\r\n");
      out.write("\t\t\t<input name=\"l_alpha\" id=\"l_alpha\" type=\"hidden\" value=\"");
      out.print(metaBean.getL_alpha());
      out.write("\"><!--언어코드 -->\r\n");
      out.write("\t\t\t<input name=\"param_id_title\" id=\"param_id_title\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_id_content\" id=\"param_id_content\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_id_url\" id=\"param_id_url\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_md_site_name\" id=\"param_md_site_name\" type=\"hidden\" value=\"\"> \r\n");
      out.write("\t\t\t<input name=\"param_id_regdate\" id=\"param_id_regdate\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_md_type\" id=\"param_md_type\" type=\"hidden\" value=\"");
      out.print(metaBean.getMd_type());
      out.write("\">\t\t\t\r\n");
      out.write("\t\t");
} else if(mode.equals("multi")){ 
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"md_seqs\" value=\"");
      out.print(md_seqs );
      out.write("\">\r\n");
      out.write("\t\t");
} else if(mode.equals("update_multi")){ 	
			if(icmBean.getId_comment() != null){
      out.write("\r\n");
      out.write("\t\t\t<input name=\"txtcmt2\" id=\"txtcmt2\" type=\"hidden\" value=\"");
      out.print(icmBean.getId_comment());
      out.write("\">\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"id_seqs\" value=\"");
      out.print(id_seqs );
      out.write("\">\r\n");
      out.write("\t\t\t<input name=\"child\" id=\"child\" type=\"hidden\" value=\"");
      out.print(child);
      out.write("\">\r\n");
      out.write("\t\t");
} else if(mode.equals("update")){
			if(idBean.getReply_count() != null){
      out.write("\r\n");
      out.write("\t\t\t<input name=\"rp_count2\" id=\"rp_count2\" type=\"hidden\" value=\"");
      out.print(idBean.getReply_count());
      out.write("\">\r\n");
      out.write("\t\t\t");
}					
			if(icmBean.getId_comment() != null){
      out.write("\r\n");
      out.write("\t\t\t<input name=\"txtcmt2\" id=\"txtcmt2\" type=\"hidden\" value=\"");
      out.print(icmBean.getId_comment());
      out.write("\">\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write(" \t\t\t<input name=\"id_seq\" id=\"id_seq\" type=\"hidden\" value=\"");
      out.print(idBean.getId_seq());
      out.write("\"><!-- 기사번호 -->\r\n");
      out.write("\t\t\t<input name=\"md_seq\" id=\"md_seq\" type=\"hidden\" value=\"");
      out.print(idBean.getMd_seq());
      out.write("\"><!-- 기사번호 -->\r\n");
      out.write("\t\t\t<input name=\"md_pseq\" id=\"md_pseq\" type=\"hidden\" value=\"");
      out.print(idBean.getMd_pseq());
      out.write("\"><!-- 모 기사번호 -->\r\n");
      out.write("\t\t\t<input name=\"s_seq\" id=\"s_seq\" type=\"hidden\" value=\"");
      out.print(idBean.getS_seq());
      out.write("\"><!-- 사이트번호 -->\r\n");
      out.write("\t\t\t<input name=\"sg_seq\" id=\"sg_seq\" type=\"hidden\" value=\"");
      out.print(idBean.getSg_seq());
      out.write("\"><!-- 사이트 그룹 -->\r\n");
      out.write("\t\t\t<input name=\"reg_type\" id=\"reg_type\" type=\"hidden\" value=\"");
      out.print(idBean.getTemp1());
      out.write("\"><!-- 사이트 그룹 -->\r\n");
      out.write("\t\t\t<input name=\"md_date\" id=\"md_date\" type=\"hidden\" value=\"");
      out.print(idBean.getMd_date());
      out.write("\"><!-- 수십 시간-->\r\n");
      out.write("\t\t\t<input name=\"md_site_menu\" id=\"md_site_menu\" type=\"hidden\" value=\"");
      out.print(idBean.getMd_site_menu());
      out.write("\"><!-- 사이트 메뉴 -->\r\n");
      out.write("\t\t\t<input name=\"id_mailyn\" id=\"id_mailyn\" type=\"hidden\" value=\"");
      out.print(idBean.getId_mailyn());
      out.write("\"><!-- 사이트 메뉴 -->\r\n");
      out.write("\t\t\t<input name=\"child\" id=\"child\" type=\"hidden\" value=\"");
      out.print(child);
      out.write("\">\r\n");
      out.write("\t\t\t<input name=\"param_id_title\" id=\"param_id_title\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_id_content\" id=\"param_id_content\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_id_url\" id=\"param_id_url\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_md_site_name\" id=\"param_md_site_name\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_id_regdate\" id=\"param_id_regdate\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_md_type\" id=\"param_md_type\" type=\"hidden\" value=\"");
      out.print(idBean.getMd_type());
      out.write("\">\r\n");
      out.write("\t\t");
} else if(mode.equals("new")){
      out.write("\r\n");
      out.write("\t\t\t<input name=\"md_seq\" id=\"md_seq\" type=\"hidden\" value=\"0\"><!-- 기사번호 -->\r\n");
      out.write("\t\t\t<input name=\"md_pseq\" id=\"md_pseq\" type=\"hidden\" value=\"0\"><!-- 모 기사번호 -->\r\n");
      out.write("\t\t\t<input name=\"s_seq\" id=\"s_seq\" type=\"hidden\" value=\"\"><!-- 사이트번호 -->\r\n");
      out.write("\t\t\t<input name=\"sg_seq\" id=\"sg_seq\" type=\"hidden\" value=\"\"><!-- 사이트 그룹 -->\r\n");
      out.write("\t\t\t<input name=\"md_date\" id=\"md_date\" type=\"hidden\" value=\"\"><!-- 수십 시간-->\r\n");
      out.write("\t\t\t<input name=\"md_site_menu\" id=\"md_site_menu\" type=\"hidden\" value=\"\"><!-- 사이트 메뉴 -->\r\n");
      out.write("\t\t\t<input name=\"md_same_ct\" id=\"md_same_ct\" type=\"hidden\" value=\"0\"><!-- 유사개수 -->\r\n");
      out.write("\t\t\t<input name=\"l_alpha\" id=\"l_alpha\" type=\"hidden\" value=\"");
      out.print("KOR");
      out.write("\"><!--언어코드 -->\r\n");
      out.write("\t\t\t<input name=\"param_id_title\" id=\"param_id_title\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_id_content\" id=\"param_id_content\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_id_url\" id=\"param_id_url\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_md_site_name\" id=\"param_md_site_name\" type=\"hidden\" value=\"\"> \r\n");
      out.write("\t\t\t<input name=\"param_id_regdate\" id=\"param_id_regdate\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t<input name=\"param_md_type\" id=\"param_md_type\" type=\"hidden\" value=\"\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div id=\"pop_head\">\r\n");
      out.write("\t");
if(mode.equals("multi")){ 
      out.write("\r\n");
      out.write("\t<p>멀티 센싱</p>\r\n");
      out.write("\t");
}else{ 
      out.write("\r\n");
      out.write("\t<p>정보 센싱</p>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<span><a href=\"javascript:close();\"><img src=\"../../images/search/pop_tit_close.gif\"></a></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
String mainStyle = "width:100%;float: right;"; 
      out.write('\r');
      out.write('\n');
      out.write('	');

					if(mode.equals("insert") || mode.equals("update") || mode.equals("new")){ 
				
      out.write("\r\n");
      out.write("\t<div style=\"width:50%;float: left;position:fixed;\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<table style=\"width:90%; margin-left: 20px;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"height:30px;\"><span class=\"sub_tit\">기본정보</span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<table id=\"board_write\" border=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><span class=\"board_write_tit\">제목</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input style=\"width:100%;\" type=\"text\" class=\"textbox2\" name=\"id_title\" value=\"");
if(mode.equals("insert")){out.print(su.ChangeString(metaBean.getMd_title()));}else if(mode.equals("new")){out.print("");} else{out.print(su.ChangeString(idBean.getId_title()));}
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><span class=\"board_write_tit\">URL</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input style=\"width:100%;\" type=\"text\" class=\"textbox2\" name=\"id_url\" value=\"");
if(mode.equals("insert")){out.print(metaBean.getMd_url());}else if(mode.equals("new")){out.print("");} else{out.print(idBean.getId_url());}
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><span class=\"board_write_tit\">출처</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:140px;\" class=\"textbox2\" name=\"id_sitegroup\">");
if(mode.equals("insert")){if(metaBean.getSg_name() !=null){ out.print(metaBean.getSg_name());}}else if(mode.equals("new")){out.print("자동등록");} else{if(idBean.getSg_name() != null){out.print(idBean.getSg_name());}}
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><span class=\"board_write_tit\">사이트이름</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input style=\"width:150px;\" type=\"text\" class=\"textbox2\" name=\"md_site_name\" value=\"");
if(mode.equals("insert")){out.print(metaBean.getMd_site_name());}else if(mode.equals("new")){out.print("");} else{out.print(idBean.getMd_site_name());}
      out.write("\"></td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><span class=\"board_write_tit\">수집시간</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input style=\"width:140px;\" type=\"text\" class=\"textbox2\" value=\"");
if(mode.equals("insert")){out.print(metaBean.getFormatMd_date("yyyy-MM-dd HH:mm:ss"));}else if(mode.equals("new")){out.print(du.getCurrentDate("yyyy-MM-dd HH:mm:ss"));} else{out.print(idBean.getFormatMd_date("yyyy-MM-dd HH:mm:ss"));}
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><span class=\"board_write_tit\">이슈등록시간</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input style=\"width:150px;\" type=\"text\" class=\"textbox2\" name=\"id_regdate\" value=\"");
if(mode.equals("insert")){out.print(du.getCurrentDate("yyyy-MM-dd HH:mm:ss"));}else if(mode.equals("new")){out.print(du.getCurrentDate("yyyy-MM-dd HH:mm:ss"));} else{out.print(idBean.getFormatId_regdate("yyyy-MM-dd HH:mm:ss"));}
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div style=\"width:85%; float: left;\">\r\n");
      out.write("\t\t\t\t\t<!-- <div style=\"font-size: x-large; text-align:center; \"> 본문 내용</div> -->\r\n");
      out.write("\t\t\t\t\t<span class=\"sub_tit\" style=\"margin-left: 20px;\">주요내용</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"padding: 30px 20px 30px 20px;\">\r\n");
      out.write("\t\t\t");

				String html = "";
				if(mode.equals("insert")){
					html = metaBean.getMd_content();
				}else{
					html = idBean.getId_content();
				}
				
			
      out.write("\r\n");
      out.write("\t\t\t\t<textarea id=\"originalView\" cols=\"86\" rows=\"24\" style=\"font-size:14px; border: 1px solid; padding:5px;;\" name=\"id_content\" >");
if(mode.equals("insert")){if(html !=null){if(metaBean.getK_value()!=null){out.print(su.cutKey(su.ChangeString(html),metaBean.getK_value(),300).trim());}else{out.print(su.cutKey(su.ChangeString(html),"",300).trim());}}}else if(mode.equals("new")){out.print("");}else{if(idBean.getId_content() != null){out.print(su.ChangeString(html));}}
      out.write("</textarea> \r\n");
      out.write("\t\t\t\t");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");

if(mode.equals("insert") || mode.equals("update") || mode.equals("new")){ 	
	mainStyle = "width:50%;float: right;";
}else{
	mainStyle = "width:100%";
}

      out.write("\r\n");
      out.write("<!-- 종료  -->\r\n");
      out.write("<div id=\"flaging\" style=\"");
      out.print(mainStyle);
      out.write("\">\r\n");
      out.write("\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"10\">\r\n");
      out.write("\t<!-- <tr>\r\n");
      out.write("\t\t<td id=\"pop_head\">\r\n");
      out.write("\t\t\t<p>이슈등록</p>\r\n");
      out.write("\t\t\t<span><a href=\"javascript:close();\"><img src=\"../../images/search/pop_tit_close.gif\"></a></span>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr> -->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<!-- 게시판 시작 -->\r\n");
      out.write("\t\t<table style=\"width:100%;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"padding-top:15px;height:45px;\"><span class=\"sub_tit\">정보분류 항목</span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<table id=\"board_write\" border=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t");

					
					arrIcBean = null;
					IssueCodeBean icBean = new IssueCodeBean();
					ArrayList<String[]> tmp_sub_type_list = null;
					String[] parentTypeArr = parentTypes.split(",");
					//String[] hycard_reqPTypeArr = hycard_requisiteParentTypes.split(",");
					//String[] hycap_reqPTypeArr = hycap_requisiteParentTypes.split(",");
					//String[] hycom_reqPTypeArr = hycom_requisiteParentTypes.split(",");
					String checked = "";
					String block = "none";
					String codes = "";
					String detailCodes = "";
					String ptype = "";
					String pcode = "";
					String requisiteSign = "";
					String typeStyle ="";
					String hycardStyle = "";
					String hycaptalStyle = "";
					String hycomStyle = "";
					String autoCheckCode  ="";
					for(String type : parentTypeArr){
						arrIcBean = icm.GetType(Integer.parseInt(type));
						checked = "";
						block = "none";
						codes = "";
						detailCodes = "";
						ptype = "";
						pcode = "";
						requisiteSign = "";
						typeStyle = "font-weight:normal;";
						hycardStyle = "font-weight:normal;color:#cc0000;";
						hycaptalStyle = "font-weight:normal;color:#0039e6";
						hycomStyle = "font-weight:normal;color:#e67300";
						
						if(arrIcBean != null){
							icBean = (IssueCodeBean) arrIcBean.get(0);	
						}
						if("update".equals(mode)){
							codes = (String)issueCodeMap.get(type);
							//detailCodes = (String)issueCodeDetailMap.get(type);
						}else if("insert".equals(mode) && autoCheckMap.size()>0 ){
							//자동맵핑 code			
							autoCheckCode = autoCheckMap.get(String.valueOf(type));
						}
/* 						
						//필수항목표시 - 현카드
						for(int r=0; r<hycard_reqPTypeArr.length; r++){
							if(hycard_reqPTypeArr[r].equals(type)){
								requisiteSign = " *";
								typeStyle = "font-weight:bold;";
							}
						}							
						//필수항목표시 - 현캐피
						for(int r=0; r<hycap_reqPTypeArr.length; r++){
							if(hycap_reqPTypeArr[r].equals(type)){
								requisiteSign = " *";
								typeStyle = "font-weight:bold;";
							}
						}							
						//필수항목표시 - 현커머
						for(int r=0; r<hycom_reqPTypeArr.length; r++){
							if(hycom_reqPTypeArr[r].equals(type)){
								requisiteSign = " *";
								typeStyle = "font-weight:bold;";
							}
						}				
 */						
						
				
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 if (type.equals("3") || type.equals("4") || type.equals("5") || type.equals("6")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"hotel\" style='display:none;' name=\"hotel\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t<th><span class=\"board_write_tit\" style=");
      out.print(hycaptalStyle);
      out.write(" id=\"typeTitle_");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(icBean.getIc_name());
      out.print(requisiteSign);
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t");
 } else if (type.equals("7") || type.equals("8")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"TR\" style='display:none;' name=\"TR\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t<th><span class=\"board_write_tit\" style=");
      out.print(hycaptalStyle);
      out.write(" id=\"typeTitle_");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(icBean.getIc_name());
      out.print(requisiteSign);
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t");
 } else if (type.equals("9") || type.equals("10")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"SHP\" style='display:none;' name=\"SHP\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t<th><span class=\"board_write_tit\" style=");
      out.print(hycaptalStyle);
      out.write(" id=\"typeTitle_");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(icBean.getIc_name());
      out.print(requisiteSign);
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t");
 } else if (type.equals("11")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"SBTM\" style='display:none;' name=\"SBTM\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t<th><span class=\"board_write_tit\" style=");
      out.print(hycaptalStyle);
      out.write(" id=\"typeTitle_");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(icBean.getIc_name());
      out.print(requisiteSign);
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t");
 } else if (type.equals("12")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"CEO\" style='display:none;' name=\"CEO\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t<th><span class=\"board_write_tit\" style=");
      out.print(hycaptalStyle);
      out.write(" id=\"typeTitle_");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(icBean.getIc_name());
      out.print(requisiteSign);
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t");
 } else if (type.equals("13")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"IR\" style='display:none;' name=\"IR\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t<th><span class=\"board_write_tit\" style=");
      out.print(hycaptalStyle);
      out.write(" id=\"typeTitle_");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(icBean.getIc_name());
      out.print(requisiteSign);
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t");
 } else if (type.equals("14")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"ESG\" style='display:none;' name=\"ESG\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t<th><span class=\"board_write_tit\" style=");
      out.print(hycaptalStyle);
      out.write(" id=\"typeTitle_");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(icBean.getIc_name());
      out.print(requisiteSign);
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"board_write_tit\" style=\"font-weight:bold;\" id=\"typeTitle_");
      out.print(type);
      out.write('"');
      out.write('>');
      out.print(icBean.getIc_name());
      out.print(requisiteSign);
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"focus_");
      out.print(type);
      out.write("_1\" value=\"\">\r\n");
      out.write("\t\t\t\t\t");

						for (int i = 1; i < arrIcBean.size(); i++) {
							
							IssueCodeBean subIcBean = (IssueCodeBean) arrIcBean.get(i);
							checked = "";
							
							if("update".equals(mode)){
								if(codes != null && !"".equals(codes)){
									String[] codeArr = codes.split(",");
									for(String codeElem : codeArr){
										if(codeElem.equals(String.valueOf(subIcBean.getIc_code()))){
											checked = "checked";
											ptype = String.valueOf(subIcBean.getIc_type());
											pcode = String.valueOf(subIcBean.getIc_code());
											break;
										}
									}
								}
							}else if("insert".equals(mode) 
									&& null!= autoCheckCode && !"".equals(autoCheckCode) 
									&& autoCheckCode.equals(String.valueOf(subIcBean.getIc_code()))
								){
								ptype = String.valueOf(subIcBean.getIc_type());
								//ptype = String.valueOf(type);
								pcode = autoCheckCode;
								checked = "checked";
							}
							
						if (type.equals("1")){	
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"typeCode");
      out.print(subIcBean.getIc_type());
      out.write('_');
      out.print(subIcBean.getIc_code() );
      out.write("\" name=\"typeCodeCheckbox_");
      out.print(subIcBean.getIc_type());
      out.write("\"  value=\"");
      out.print(subIcBean.getIc_type());
      out.write(',');
      out.print(subIcBean.getIc_code() );
      out.write("\"  onclick=\"HyDisplay(");
      out.print(subIcBean.getIc_type());
      out.write(',');
      out.print(subIcBean.getIc_code());
      out.write(",'1',");
      out.print(type);
      out.write(");\" ");
      out.print(checked );
      out.write(" />\r\n");
      out.write("\t\t\t\t\t\t");
 } else if(!type.equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"typeCode");
      out.print(subIcBean.getIc_type());
      out.write('_');
      out.print(subIcBean.getIc_code() );
      out.write("\" name=\"typeCodeCheckbox_");
      out.print(subIcBean.getIc_type());
      out.write("\"  value=\"");
      out.print(subIcBean.getIc_type());
      out.write(',');
      out.print(subIcBean.getIc_code() );
      out.write("\"  onclick=\"getSubDepth(");
      out.print(subIcBean.getIc_type());
      out.write(',');
      out.print(subIcBean.getIc_code() );
      out.write(",'1',");
      out.print(type);
      out.write(");\" ");
      out.print(checked );
      out.write(" />\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<label for=\"typeCode");
      out.print(subIcBean.getIc_type());
      out.write('_');
      out.print(subIcBean.getIc_code() );
      out.write("\" style=\"cursor:pointer\">");
      out.print(subIcBean.getIc_name() );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t");
  
							if( i != 1 && i%5==0 ) {
								out.print("<br>");
							}
						}
				
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

				String colsapn="3";					
				block = "none";
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 하위 -->\r\n");
      out.write("\t\t\t\t\t");
						
					  	tmp_sub_type_list = subDepthList.get(type);
						
						if(null!=tmp_sub_type_list && tmp_sub_type_list.size()>0){
							for(int t=0; t<tmp_sub_type_list.size();t++){
								block = "none";
								if("update".equals(mode)){
									detailCodes = (String)issueCodeMap.get(tmp_sub_type_list.get(t)[2]);
									if(null!=(detailCodes) && !"".equals(ptype)&& !"".equals(pcode)){										
										subArrIcBean = icm.getSearchIssueCode(ptype, pcode);
										if(null != subArrIcBean && subArrIcBean.size()>0){
											block = "";	
											typeStyle = "font-weight:normal;";
										}
													
									}
								}else if("insert".equals(mode) && ( null != autoCheckMap && autoCheckMap.size()>0 )){
									if(!"".equals(ptype)&& !"".equals(pcode) 
										&& null!=autoCheckMap.get(String.valueOf(tmp_sub_type_list.get(t)[2]))
										&& !"".equals(autoCheckMap.get(String.valueOf(tmp_sub_type_list.get(t)[2]))) 
									){
										autoCheckCode = autoCheckMap.get(String.valueOf(tmp_sub_type_list.get(t)[2]));
										subArrIcBean = icm.getSearchIssueCode(ptype, pcode);
										if(null != subArrIcBean && subArrIcBean.size()>0){
											block = "";	
											typeStyle = "font-weight:normal;";
										}
									}
								}
										
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t    <tr id=\"tr_typeCode");
      out.print(type);
      out.write("_subDepth_");
      out.print(t+2);
      out.write("\" style='display:");
      out.print(block);
      out.write(";'  data-depth=\"");
      out.print(t+2);
      out.write("\" name=\"tr_typeCode_");
      out.print(type);
      out.write("\" value=\"");
      out.print(type);
      out.write(',');
      out.print(t+2);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"background-color: #F8F8F8;\"><span style=\"padding-left:10px; ");
      out.print(typeStyle);
      out.write("\"><img alt=\"하위분류\" src=\"../../images/issue/icon_bot_02.gif\">");
      out.print(tmp_sub_type_list.get(t)[1] );
      out.write("</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td id=\"td_typeCode");
      out.print(type);
      out.write("_subDepth_");
      out.print(t+2);
      out.write("\" colspan=\"");
      out.print(colsapn);
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"focus_");
      out.print(type);
      out.write('_');
      out.print(t+2);
      out.write("\" value=\"\"> <!-- 라디오 박스 해제용 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								if( 
									("update".equals(mode) && ( null != subArrIcBean && subArrIcBean.size()>0 ))
									|| 	("insert".equals(mode) && ( null != subArrIcBean && subArrIcBean.size()>0 )&& ( null != autoCheckMap && autoCheckMap.size()>0 ))
								 ){											
									for (int i = 0; i < subArrIcBean.size(); i++) {	
										IssueCodeBean subIcBean = (IssueCodeBean) subArrIcBean.get(i);
										checked = "";
										if("update".equals(mode)){
											if(String.valueOf(subIcBean.getIc_code()).equals(detailCodes)){											
												String[] codeArr = detailCodes.split(",");
												
													for(String codeElem : codeArr){
														if(codeElem.equals(String.valueOf(subIcBean.getIc_code()))){
															checked = "checked";
															ptype=String.valueOf(subIcBean.getIc_type());
															pcode=String.valueOf(subIcBean.getIc_code());
															break;
														}
													}
											}
										}else if ("insert".equals(mode) && null != autoCheckCode && !"".equals(autoCheckCode)){
											if(autoCheckCode.equals(String.valueOf(subIcBean.getIc_code()))){
												checked = "checked";
												ptype = String.valueOf(subIcBean.getIc_type());
												pcode = String.valueOf(subIcBean.getIc_code());		
											}
										}
										
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type='radio' id=\"input_info");
      out.print(subIcBean.getIc_type());
      out.write('_');
      out.print(subIcBean.getIc_code());
      out.write("\" name=\"input_infoAttr_");
      out.print(subIcBean.getIc_type());
      out.write("\" value=\"");
      out.print(subIcBean.getIc_type());
      out.write(',');
      out.print(subIcBean.getIc_code());
      out.write("\"  data-group=\"");
      out.print(type);
      out.write("\" data-depth=\"");
      out.print(t+2);
      out.write("\" onclick=\"getSubDepth(");
      out.print(subIcBean.getIc_type());
      out.write(',');
      out.print(subIcBean.getIc_code());
      out.write(',');
      out.print(t+2);
      out.write(',');
      out.print(type);
      out.write(");\" ");
      out.print(checked );
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"input_info");
      out.print(subIcBean.getIc_type());
      out.write('_');
      out.print(subIcBean.getIc_code());
      out.write("\" style=\"cursor:pointer;\">");
      out.print(subIcBean.getIc_name() );
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if((i+1)%5==0 && i!=0) {
											out.print("<br>");
										}
									}
								}
								 
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
						
						 }
				  }
				}
				
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><span class=\"board_write_tit\">영향력</span></th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"clout_power\" name=\"typeCodeCheckbox_clout\" value=\"1\" onclick=\"chk_clout(this.value)\" ");
if( "update".equals(mode) && "1".equals(idBean.getId_clout())){out.println("checked = checked");}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"clout_power\" style=\"cursor:pointer\">파워</label>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"clout_normal\" name=\"typeCodeCheckbox_clout\" value=\"2\" onclick=\"chk_clout(this.value)\" ");
if( "update".equals(mode) && "2".equals(idBean.getId_clout())){out.println("checked = checked");}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"clout_normal\" style=\"cursor:pointer\">일반</label>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 라디오 박스 해제용 -->\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"focus_clout\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><span class=\"board_write_tit\">성향</span></th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"senti_pos\" name=\"typeCodeCheckbox_senti\" value=\"1\" onclick=\"chk_senti(this.value)\" ");
if( "update".equals(mode) && "1".equals(idBean.getId_senti())){out.println("checked = checked");}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"senti_pos\" style=\"cursor:pointer\">긍정</label>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"senti_neg\" name=\"typeCodeCheckbox_senti\" value=\"2\" onclick=\"chk_senti(this.value)\" ");
if( "update".equals(mode) && "2".equals(idBean.getId_senti())){out.println("checked = checked");}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"senti_neg\" style=\"cursor:pointer\">부정</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"senti_neu\" name=\"typeCodeCheckbox_senti\" value=\"3\" onclick=\"chk_senti(this.value)\" ");
if( "update".equals(mode) && "3".equals(idBean.getId_senti())){out.println("checked = checked");}
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"senti_neu\" style=\"cursor:pointer\">중립</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 라디오 박스 해제용 -->\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"focus_senti\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><span class=\"board_write_tit\">보고서</span></th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"trans_yes\" name=\"typeCodeCheckbox_trans\" value=\"Y\" onclick=\"chk_trans(this.value)\" ");
if( "update".equals(mode) && "Y".equals(idBean.getId_reportyn())){out.println("checked = checked");}
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"trans_yes\" style=\"cursor:pointer\">포함</label>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"trans_no\" name=\"typeCodeCheckbox_trans\" value=\"N\" onclick=\"chk_trans(this.value)\" ");
if( "update".equals(mode) && "N".equals(idBean.getId_reportyn()) || "insert".equals(mode) || "multi".equals(mode)|| "new".equals(mode)){out.println("checked = checked");}
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"trans_no\" style=\"cursor:pointer\">미포함</label>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 라디오 박스 해제용 -->\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"focus_trans\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th><span class=\"board_write_tit\" style=\"font-weight:bold;\">연관키워드</span></th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"500\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"500\" style=\"border-bottom:0px #CCCCCC dotted;\" id=\"select_keyword\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"3\" id=\"remakeRelationwordText\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"input_keyword\" id=\"txt_relationkey\" name=\"txt_relationkey\" onkeypress=\"javascript:if(event.keyCode == 13){ addKeyword();}\" placeholder=\"연관키워드 입력\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"../../images/issue/plus_btn.gif\" onclick=\"addKeyword();\" style=\"vertical-align: bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										String[] relKeyArr = null;
									 	if("update".equals(mode) && null!=relationkeywordR_str && !"".equals(relationkeywordR_str)) {
									 		relKeyArr = relationkeywordR_str.split("@");
									 		String[] code_word = new String[2];  									 		
									 		for(int i=0; i < relKeyArr.length; i++){
									 			code_word = relKeyArr[i].split(":");  
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span id='keyword_");
      out.print(code_word[1]);
      out.write('_');
      out.print(i);
      out.write("' class='keyNm'>");
      out.print(code_word[0]);
      out.write("&nbsp;<img src=\"../../images/issue/delete_btn_01.gif\" style=\"vertical-align: middle; cursor:pointer;\" onclick=\"delKeyword('");
      out.print(i);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(code_word[1]);
      out.write("')\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
			
										 		}
										 	}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"text-align:center;\"><font id=\"fnMsg\" style=\"color: #5364D2; font-weight: bold; font-size: 13px;\" ></font></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"text-align:center;\"><img src=\"../../images/search/btn_save_2.gif\" onclick=\"save_issue('");
      out.print(mode);
      out.write("');\" style=\"cursor:pointer;\"/>&nbsp;<img src=\"../../images/search/btn_cancel.gif\" onclick=\"window.close();\" style=\"cursor:pointer;\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
